apiVersion: v1
kind: Secret
metadata:
  name: university-ecosystem-db
  labels:
    {{- include "university-ecosystem.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 for postgresql+psycopg://university:local_dev_pg_password_ChangeMe_123456@university-ecosystem-postgresql:5432/university
  url: cG9zdGdyZXNxbCtwc3ljb3BnMiovL3VuaXZlcnNpdHk6bG9jYWxfZGV2X3BnX3Bhc3N3b3JkX0NoYW5nZU1lXzEyMzQ1NkB1bml2ZXJzaXR5LWVjb3N5c3RlbS1wb3N0Z3Jlc3FsOjU0MzIvdW5pdmVyc2l0eQ==

---
apiVersion: v1
kind: Secret
metadata:
  name: university-ecosystem-db-pass
  labels:
    {{- include "university-ecosystem.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 for local_dev_pg_password_ChangeMe_123456
  postgres-password: bG9jYWxfZGV2X3BnX3Bhc3N3b3JkX0NoYW5nZU1lXzEyMzQ1Ng==
  password: bG9jYWxfZGV2X3BnX3Bhc3N3b3JkX0NoYW5nZU1lXzEyMzQ1Ng==

---
apiVersion: v1
kind: Secret
metadata:
  name: university-ecosystem-secrets
  labels:
    {{- include "university-ecosystem.labels" . | nindent 4 }}
type: Opaque
data:
  # Base64 for a sample secret
  audit-log-secret: c3VwZXItc2VjcmV0LWNoYW5nZS1tZQ==
