"""Canonical URLs and storage-key validation for private attachments."""

from __future__ import annotations

import mimetypes
import re
from typing import Final, Literal
from urllib.parse import unquote, urlparse

from starlette.responses import Response

PrivateAttachmentKind = Literal["chat", "event"]

_PREFIXES: dict[PrivateAttachmentKind, str] = {
    "chat": "chat_uploads",
    "event": "event_files",
}
_FILENAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,255}$")
_RESOURCE_ID_RE = re.compile(r"^[A-Za-z0-9-]{1,64}$")
_FLAT_FILENAME_RE = re.compile(
    r"^(?:chat|event)_[A-Za-z0-9-]{1,64}_[0-9a-fA-F]{32}"
    r"(?:\.[A-Za-z0-9][A-Za-z0-9._-]{0,63})?$"
)

# Keep protocol field names outside request handling functions.  HTTP header
# names are case-insensitive, so mutating their spelling inside the function
# would create equivalent mutants that no response-level test can distinguish.
_CACHE_CONTROL_HEADER: Final = "Cache-Control"
_CONTENT_DISPOSITION_HEADER: Final = "Content-Disposition"
_CONTENT_TYPE_OPTIONS_HEADER: Final = "X-Content-Type-Options"


def _safe_filename(filename: str) -> str | None:
    if not filename or not _FILENAME_RE.fullmatch(filename):
        return None
    return filename


def _safe_resource_id(resource_id: object) -> str:
    value = str(resource_id).strip()
    if not _RESOURCE_ID_RE.fullmatch(value):
        raise ValueError("Invalid attachment resource id")
    return value


def _is_safe_resource_id(resource_id: object) -> bool:
    """Non-raising form of :func:`_safe_resource_id` for branch conditions."""

    try:
        _safe_resource_id(resource_id)
    except ValueError:
        return False
    return True


def _path_segments(storage_url: str) -> list[str]:
    raw = str(storage_url or "").strip()
    if not raw:
        return []
    parsed = urlparse(raw)
    # ``partition`` keeps only the first query delimiter without exposing a
    # max-split parameter whose equivalent mutations cannot be distinguished.
    path = parsed.path if parsed.scheme or parsed.netloc else raw.partition("?")[0]
    # ``image_proxy._sanitize_path_input`` applies URL decoding repeatedly;
    # perform the same canonicalisation before classifying a path so an
    # over-encoded private prefix cannot reach a public transformation route.
    decoded = path
    while True:
        previous = decoded
        decoded = unquote(decoded)
        if decoded == previous:
            break
    decoded = decoded.replace("\\", "/")
    return [segment for segment in decoded.split("/") if segment]


def private_attachment_filename(
    storage_url: str, kind: PrivateAttachmentKind
) -> str | None:
    """Extract a validated generated filename from a private storage URL."""

    segments = _path_segments(storage_url)
    prefix = _PREFIXES[kind]
    for index, segment in enumerate(segments):
        if segment != prefix:
            continue
        # Match on the tail rather than on index arithmetic.  Both the bounds
        # guard and the ``continue`` that used to guard the resource-id check
        # were unobservable -- every branch below already pins the exact tail
        # length -- so they only produced equivalent mutants against the 100%
        # gate (run 35517610350 left three of them alive).
        tail = segments[index + 1 :]

        # Current uploads are flat keys generated by ``save_attachment``:
        # ``<prefix>/<kind>_<resource>_<random-hex>.<ext>``.
        if len(tail) == 1:
            candidate = _safe_filename(tail[0])
            if candidate and _FLAT_FILENAME_RE.fullmatch(candidate):
                return candidate

        # Keep compatibility with the hierarchical key shape used by older
        # deployments and by storage-key builders.
        if len(tail) == 2 and tail[0].startswith(f"{kind}_"):
            candidate = _safe_filename(tail[1])
            if candidate and _is_safe_resource_id(tail[0][len(kind) + 1 :]):
                return candidate
    return None


def is_private_attachment_path(storage_url: str) -> bool:
    """Return whether a storage path belongs to a protected attachment prefix."""

    segments = _path_segments(storage_url)
    return any(segment in _PREFIXES.values() for segment in segments)


def private_attachment_url(
    kind: PrivateAttachmentKind, resource_id: object, storage_url: str
) -> str:
    """Map a private storage URL to an authorized API download URL.

    Public media and legacy test/storage values outside the private prefixes are
    returned unchanged for compatibility.  A malformed value under a private
    prefix fails closed instead of leaking its original URL.
    """

    # ``_path_segments`` already coerces and strips, and
    # ``private_attachment_filename`` routes through it too, so normalizing
    # again here only duplicated that step and left an equivalent mutant
    # behind (run 35517610350).
    segments = _path_segments(storage_url)
    if any(segment in _PREFIXES.values() for segment in segments):
        filename = private_attachment_filename(storage_url, kind)
        if filename is None:
            return ""
        safe_id = _safe_resource_id(resource_id)
        resource = "chats" if kind == "chat" else "events"
        child = "attachments" if kind == "chat" else "files"
        return f"/api/v1/{resource}/{safe_id}/{child}/{filename}"
    return storage_url


def private_attachment_storage_key(
    kind: PrivateAttachmentKind, resource_id: object, filename: str
) -> str:
    """Build the expected private storage key after strict path validation."""

    safe_id = _safe_resource_id(resource_id)
    safe_filename = _safe_filename(filename)
    # ``_safe_filename`` rejects path separators through its anchored
    # allow-list, so a single sentinel check is the complete validation gate.
    if safe_filename is None:
        raise ValueError("Invalid attachment filename")
    return f"{_PREFIXES[kind]}/{kind}_{safe_id}/{safe_filename}"


def private_attachment_response(data: bytes, filename: str) -> Response:
    """Return attachment bytes with non-shareable, content-sniff-safe headers."""

    media_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
    return Response(
        content=data,
        media_type=media_type,
        headers={
            _CACHE_CONTROL_HEADER: "private, no-store",
            _CONTENT_DISPOSITION_HEADER: f'inline; filename="{filename}"',
            _CONTENT_TYPE_OPTIONS_HEADER: "nosniff",
        },
    )
