exclude-rules = [
  "prefer-robust-stmts",
  "prefer-text-field",
  "require-timeout-settings",
  "prefer-bigint-over-int",
  "prefer-identity",
  "prefer-timestamp-tz",
  "require-concurrent-index-creation",
  "constraint-missing-not-valid",
  "disallowed-unique-constraint",
  "require-if-not-exists",
  "require-lock-timeout",
  "prefer-text-to-varchar",
  "require-concurrent-drop-index",
  "disallowed-foreign-key-constraint",
  "disallowed-drop-table",
  "disallowed-drop-column",
  "disallowed-rename-column",
  "disallowed-rename-table",
]
