services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --env-file root/.env
    working_dir: /workspace/root
    volumes:
      - .:/workspace:cached
    env_file:
      - root/.env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/university
      FRONTEND_ORIGIN: http://localhost:5173
      FRONTEND_ORIGINS: http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    image: node:20-alpine
    working_dir: /workspace/root/frontend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    environment:
      VITE_BACKEND_ORIGIN: http://localhost:8000
    volumes:
      - .:/workspace:cached
      - frontend-node-modules:/workspace/root/frontend/node_modules
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: university
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

volumes:
  postgres-data:
  frontend-node-modules:
