# syntax=docker/dockerfile:1.12

# Stage 1: Base
FROM node:24-alpine@sha256:01743339035a5c3c11a373cd7c83aeab6ed1457b55da6a69e014a95ac4e4700b AS base
WORKDIR /app

# Stage 2: WASM — build Rust WASM packages (rust-crypto + wasm-sanitizer)
FROM rust:1.94.1-slim-bookworm@sha256:5ae2d2ef9875c9c2407bf9b5678e6375304f7ecf8ea46b23e403a5690ec357ec AS wasm-builder
RUN cargo install wasm-pack --locked
WORKDIR /wasm
COPY frontend/rust-crypto ./rust-crypto
COPY frontend/wasm-sanitizer ./wasm-sanitizer
RUN wasm-pack build rust-crypto --target web \
 && wasm-pack build wasm-sanitizer --target web

# Stage 3: Dependencies
FROM base AS deps
COPY frontend/package.json frontend/package-lock.json ./
COPY frontend/scripts ./scripts/
RUN --mount=type=cache,target=/root/.npm \
  npm ci --legacy-peer-deps

# Stage 4: Builder
FROM base AS builder
ARG VITE_BACKEND_ORIGIN=""
ENV VITE_BACKEND_ORIGIN=$VITE_BACKEND_ORIGIN
COPY --from=deps /app/node_modules ./node_modules
COPY frontend ./
# Copy pre-built WASM packages (FIX-44-02: prevents silent WASM build failure)
COPY --from=wasm-builder /wasm/rust-crypto/pkg ./rust-crypto/pkg
COPY --from=wasm-builder /wasm/wasm-sanitizer/pkg ./wasm-sanitizer/pkg
RUN npm run build

# Stage 5: Production-only dependencies (Wave 131 SW3 — Node SSR runtime)
# Mirrors the `deps` stage but with `--omit=dev` so the runtime image does
# not ship Storybook / Vite / Vitest / Playwright / etc. (~60 devDependencies).
# `dist/server/server.js` imports external runtime deps (react, @tanstack/*,
# h3-v2, seroval, jose, ...) that must be resolvable at runtime.
FROM base AS prod-deps
COPY frontend/package.json frontend/package-lock.json ./
COPY frontend/scripts ./scripts/
# Drop dev-only lifecycle scripts before `npm ci`:
#   - `prepare` runs `husky ../.husky` (Git hooks setup); husky lives in
#     devDependencies so it's missing under `--omit=dev` → exit code 127.
#   - `postinstall` runs `setup-lhci-binaries.cjs` which downloads Chrome
#     (~50 MB) for LHCI testing; pure dev-time, not needed in runtime.
# `preinstall` (ensure-wasm.mjs that creates placeholder pkg/ dirs for the
# wasm-sanitizer + rust-crypto file:// deps) is preserved and still runs.
RUN npm pkg delete scripts.prepare scripts.postinstall
RUN --mount=type=cache,target=/root/.npm \
  npm ci --omit=dev --legacy-peer-deps

# Stage 6: Runtime — Node SSR (Wave 131 Phase 4)
# Replaces the prior `nginxinc/nginx-unprivileged:1.28.2-alpine` runtime
# that just served a static SPA shell. tanstackStart's server entry
# (`dist/server/server.js`, generated by `npm run build`) is bound to a
# standard Node `http.createServer` via the thin `scripts/server-prod.mjs`
# wrapper introduced in W131 SW1. Listens on PORT env (default 3000) on
# 0.0.0.0; Caddy `health_uri` + k8s livenessProbe / readinessProbe hit
# `/healthz` (W131 SW2 fast path that short-circuits before SSR).
#
# Note: `frontend/nginx.conf` is no longer referenced from this Dockerfile
# but remains in the source tree as documentation of the prior production
# routing rules. A future polish wave may remove it once the Phase 6
# rollout (W132+) confirms no fallback is needed.
FROM node:24-alpine@sha256:01743339035a5c3c11a373cd7c83aeab6ed1457b55da6a69e014a95ac4e4700b AS runtime

WORKDIR /app

# package.json is needed at runtime so Node resolves "type": "module"
# correctly and so the wasm-sanitizer / rust-crypto file:// references
# (declared as runtime dependencies) match the node_modules layout.
COPY --from=prod-deps --chown=node:node /app/package.json ./package.json

# Production-only node_modules — no devDependencies. ~150 MB → ~80 MB
# vs full deps (saves Storybook/Playwright/Vitest/etc.).
COPY --from=prod-deps --chown=node:node /app/node_modules ./node_modules

# server-prod.mjs Node wrapper (W131 SW1) — imports dist/server/server.js
# default export, adapts Web Standards Request <-> Node IncomingMessage,
# binds http.createServer on PORT/HOST.
COPY --chown=node:node frontend/scripts/server-prod.mjs ./scripts/server-prod.mjs

# Build artifacts:
#   dist/client/_shell.html + dist/client/index.html (mirror) + dist/client/assets/
#   dist/server/server.js (tanstackStart server entry — what wrapper imports)
#   dist/sw.js + dist/sw.js.map (PWA service worker)
COPY --from=builder --chown=node:node /app/dist ./dist

# Drop to non-root `node` user (UID/GID 1000, built into node:alpine images).
USER node

ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

# Health check hits /healthz fast path. wget is provided by busybox in
# alpine images; --spider sends HEAD only (no body download).
# start-period 15s gives Node enough time to import server.js + bind port
# on cold start; subsequent intervals are 30s.
HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget --quiet --tries=1 --spider http://127.0.0.1:3000/healthz || exit 1

CMD ["node", "scripts/server-prod.mjs"]
