[mypy]
python_version = 3.11
mypy_path = .
plugins = pydantic.mypy
namespace_packages = True
ignore_missing_imports = True
allow_untyped_defs = True
allow_untyped_globals = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
show_error_codes = True
follow_imports = normal
files = app/services/notification_templates.py, app/utils/images.py
