<#
.SYNOPSIS
    Start the University Ecosystem site using Docker Compose.

.DESCRIPTION
    Builds and starts all Docker containers for the full site.
    Generates secure secrets if .env / .env.docker don't exist.
    Creates MinIO bucket and SpiceDB database on first run.

.EXAMPLE
    .\start-docker.ps1            # Start (no rebuild)
    .\start-docker.ps1 -Build     # Build (cached) then start
    .\start-docker.ps1 -Rebuild   # Build (no-cache) then start
    .\start-docker.ps1 -Down      # Stop all containers
    .\start-docker.ps1 -Logs                  # Follow all logs
    .\start-docker.ps1 -Logs -LogService backend  # Follow one service
#>

param(
    [switch]$Build,
    [switch]$Rebuild,
    [switch]$Down,
    [switch]$Logs,
    [string]$LogService = ""
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $ProjectRoot

$ComposeFile = "docker-compose.full.yml"
$EnvFile = ".env.docker"
$EnvCompose = ".env"

# -- Helpers ------------------------------------------------------------------

function Write-Status  { param([string]$Msg) Write-Host "[*] $Msg" -ForegroundColor Cyan }
function Write-Ok      { param([string]$Msg) Write-Host "[+] $Msg" -ForegroundColor Green }
function Write-Err     { param([string]$Msg) Write-Host "[-] $Msg" -ForegroundColor Red }
function Write-Warn    { param([string]$Msg) Write-Host "[!] $Msg" -ForegroundColor Yellow }

function New-Secret {
    param([int]$Length = 32)
    $chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
    -join ((1..$Length) | ForEach-Object { $chars[(Get-Random -Maximum $chars.Length)] })
}

function New-HexSecret {
    param([int]$Length = 32)
    -join ((1..$Length) | ForEach-Object { '{0:x2}' -f (Get-Random -Maximum 256) })
}

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    [System.IO.File]::WriteAllText(
        (Join-Path $ProjectRoot $Path),
        $Content,
        [System.Text.UTF8Encoding]::new($false)
    )
}

# Wave 137 SW1: Generate RSA-2048 keypair for backend JWT RS256 signing.
# Idempotent - skips generation if key file already exists.
# Uses .NET 8 native PEM export (PowerShell 7+ ships .NET 8 with
# RSA.ExportPkcs8PrivateKeyPem). Falls back to OpenSSL if available.
# Closes W135 sec.Honesty #9 SSR auth-at-edge layer (jose.createRemoteJWKSet
# requires RS256; pre-W137 dev backend signed HS256).
function New-JwtRs256Key {
    param([string]$OutputPath = ".secrets/jwt_rs256.pem")

    $absoluteOutputPath = Join-Path $ProjectRoot $OutputPath
    if (Test-Path $absoluteOutputPath) {
        Write-Ok "RSA-2048 keypair already exists at $OutputPath (idempotent skip)"
        return
    }

    Write-Status "Generating RSA-2048 keypair for JWT RS256 signing..."

    $secretsDir = Split-Path $absoluteOutputPath -Parent
    if (-not (Test-Path $secretsDir)) {
        New-Item -ItemType Directory -Path $secretsDir -Force | Out-Null
    }

    $pem = $null
    try {
        # Path A: .NET 8 native PEM export (preferred, no external deps)
        $rsa = [System.Security.Cryptography.RSA]::Create(2048)
        try {
            $pem = $rsa.ExportPkcs8PrivateKeyPem()
        } finally {
            $rsa.Dispose()
        }
    } catch {
        # Path B: host openssl fallback (requires openssl in PATH)
        if (Get-Command openssl -ErrorAction SilentlyContinue) {
            $tempKey = [System.IO.Path]::GetTempFileName()
            try {
                $null = openssl genrsa -out $tempKey 2048 2>&1
                if ($LASTEXITCODE -eq 0) {
                    $pem = Get-Content $tempKey -Raw
                }
            } finally {
                Remove-Item $tempKey -ErrorAction SilentlyContinue
            }
        }

        # Path C: docker fallback (runs openssl in lightweight container if host openssl unavailable)
        if (-not $pem -and (Get-Command docker -ErrorAction SilentlyContinue)) {
            Write-Status "Falling back to Docker openssl for keypair generation..."
            $pem = docker run --rm alpine sh -c "apk add --no-cache openssl >/dev/null 2>&1; openssl genrsa 2048 2>/dev/null" 2>&1 | Out-String
            if ($LASTEXITCODE -ne 0 -or $pem -notmatch "BEGIN (RSA )?PRIVATE KEY") {
                $pem = $null
            }
        }
    }

    if (-not $pem) {
        throw "Failed to generate RSA private key - neither .NET, host openssl, nor docker openssl succeeded."
    }

    [System.IO.File]::WriteAllText(
        $absoluteOutputPath,
        $pem.Trim(),
        [System.Text.UTF8Encoding]::new($false)
    )

    Write-Ok "Generated RSA-2048 keypair at $OutputPath"
}

# Wave 142 SW3: derive RSA-2048 PUBLIC key from existing private key for
# Temporal's JWT verification (TEMPORAL_JWT_KEY_SOURCE1=file:///app/.secrets/
# jwt_rs256.pub.pem). The private key is generated by New-JwtRs256Key (above);
# the public key is needed because Temporal verifies JWT signatures it CANNOT
# sign. Uses .NET 8 RSA.ExportSubjectPublicKeyInfoPem with openssl fallback.
# Idempotent: skips if .secrets/jwt_rs256.pub.pem already exists. Closes
# W141 (z) #4 risk by avoiding the HTTP-JWKS chicken-and-egg with backend
# startup ordering - file:// URLs require no network roundtrip at temporal
# server startup, so Temporal won't fail JWKS fetch if backend isn't yet
# healthy. The backend's /.well-known/jwks.json endpoint serves the SAME
# public key derivation server-side; this file is just the static copy
# Temporal reads at boot.
function New-JwtRs256PublicKey {
    param(
        [string]$PrivateKeyPath = ".secrets/jwt_rs256.pem",
        [string]$OutputPath = ".secrets/jwt_rs256.pub.pem"
    )

    $absolutePrivateKeyPath = Join-Path $ProjectRoot $PrivateKeyPath
    $absoluteOutputPath = Join-Path $ProjectRoot $OutputPath

    if (Test-Path $absoluteOutputPath) {
        Write-Ok "RSA-2048 public key already exists at $OutputPath (idempotent skip)"
        return
    }

    if (-not (Test-Path $absolutePrivateKeyPath)) {
        throw "Cannot derive public key: private key not found at $PrivateKeyPath. Run New-JwtRs256Key first."
    }

    Write-Status "Deriving RSA-2048 public key from $PrivateKeyPath..."

    $publicPem = $null
    try {
        # Path A: .NET 8 native - RSA.ImportFromPem + ExportSubjectPublicKeyInfoPem
        $privatePem = [System.IO.File]::ReadAllText($absolutePrivateKeyPath)
        $rsa = [System.Security.Cryptography.RSA]::Create()
        try {
            $rsa.ImportFromPem($privatePem)
            $publicPem = $rsa.ExportSubjectPublicKeyInfoPem()
        } finally {
            $rsa.Dispose()
        }
    } catch {
        # Path B: host openssl fallback (requires openssl in PATH)
        if (Get-Command openssl -ErrorAction SilentlyContinue) {
            $publicPem = openssl rsa -in $absolutePrivateKeyPath -pubout 2>&1 | Out-String
            if ($LASTEXITCODE -ne 0) {
                $publicPem = $null
            }
        }

        # Path C: docker fallback (mounts .secrets dir and runs openssl rsa -pubout)
        if (-not $publicPem -and (Get-Command docker -ErrorAction SilentlyContinue)) {
            $secretDirAbs = Split-Path $absolutePrivateKeyPath -Parent
            $privKeyFile = Split-Path $absolutePrivateKeyPath -Leaf
            $publicPem = docker run --rm -v "${secretDirAbs}:/secrets:ro" alpine sh -c "apk add --no-cache openssl >/dev/null 2>&1; openssl rsa -in /secrets/${privKeyFile} -pubout 2>/dev/null" 2>&1 | Out-String
            if ($LASTEXITCODE -ne 0 -or $publicPem -notmatch "BEGIN PUBLIC KEY") {
                $publicPem = $null
            }
        }
    }

    if (-not $publicPem) {
        throw "Failed to derive RSA public key - neither .NET, host openssl, nor docker openssl succeeded."
    }

    [System.IO.File]::WriteAllText(
        $absoluteOutputPath,
        $publicPem.Trim(),
        [System.Text.UTF8Encoding]::new($false)
    )

    Write-Ok "Derived RSA-2048 public key at $OutputPath"
}

# Wave 141 SW4: helper for base64url encoding (JWT spec). Used by
# New-TemporalServiceToken below. Generic enough to share with future helpers.
function ConvertTo-Base64Url {
    param([Parameter(Mandatory=$true)][byte[]]$Bytes)
    return [System.Convert]::ToBase64String($Bytes).TrimEnd('=').Replace('+', '-').Replace('/', '_')
}

# Wave 141 SW4: mint long-lived service token (~1 year exp) signed with the
# same RSA private key backend uses for its JWTs. Token has sub=
# file-processor-service + aud=temporal claims so Temporal's default JWT claim
# mapper (W141 SW2 verified - common/authorization/default_jwt_claim_mapper.go)
# recognizes it via the JWKS endpoint at /.well-known/jwks.json.
#
# Closes W137 sec.Honesty #5 + W140 NEW #6 (joined with SW3 image swap + SW5 Go
# credentials attach to form the full Path (a-auth) chain).
#
# Idempotent: skips minting if .secrets/temporal_api_key already exists. To
# regenerate (e.g., changed audience), delete the file and re-run.
#
# Security framing: this is a STATIC long-lived service token (no rotation).
# Acceptable for dev compose where the threat model is "anyone with host
# filesystem access". Production K8s deployments use managed Temporal Cloud /
# Helm chart with proper rotation infrastructure - this token NEVER ships to
# production.
#
# Issue temporalio/temporal#8218 mitigation: subject claim name is hardcoded
# as "sub" in default_jwt_claim_mapper.go:19. We mint with sub=
# file-processor-service to match this hardcoded expectation.
function New-TemporalServiceToken {
    param(
        [string]$PrivateKeyPath = ".secrets/jwt_rs256.pem",
        [string]$OutputPath = ".secrets/temporal_api_key",
        [string]$Subject = "file-processor-service",
        [string]$Audience = "temporal",
        [int]$ExpirationSeconds = 31536000  # 1 year (dev-only)
    )

    $absoluteOutputPath = Join-Path $ProjectRoot $OutputPath
    if (Test-Path $absoluteOutputPath) {
        Write-Ok "Temporal service token already exists at $OutputPath (idempotent skip)"
        return
    }

    $absolutePrivateKeyPath = Join-Path $ProjectRoot $PrivateKeyPath
    if (-not (Test-Path $absolutePrivateKeyPath)) {
        throw "Cannot mint Temporal service token: private key not found at $PrivateKeyPath. Run New-JwtRs256Key first."
    }

    $days = [Math]::Round($ExpirationSeconds / 86400)
    Write-Status "Minting Temporal service token (sub=$Subject, aud=$Audience, $days days valid)..."

        $headerObj  = [PSCustomObject]@{ alg = 'RS256'; kid = 'primary'; typ = 'JWT' }
        $payloadObj = [PSCustomObject]@{
            sub = $Subject
            aud = $Audience
            iat = $now
            exp = $exp
            jti = $jti
        }

        $headerJson  = $headerObj  | ConvertTo-Json -Compress
        $payloadJson = $payloadObj | ConvertTo-Json -Compress

        $headerB64  = ConvertTo-Base64Url ([System.Text.Encoding]::UTF8.GetBytes($headerJson))
        $payloadB64 = ConvertTo-Base64Url ([System.Text.Encoding]::UTF8.GetBytes($payloadJson))

        $signingInput = "$headerB64.$payloadB64"

        $signatureB64 = $null
        try {
            # Path A: .NET 8 native - RSA.ImportFromPem + SignData
            $pem = [System.IO.File]::ReadAllText($absolutePrivateKeyPath)
            $rsa = [System.Security.Cryptography.RSA]::Create()
            try {
                $rsa.ImportFromPem($pem)
                $signingInputBytes = [System.Text.Encoding]::UTF8.GetBytes($signingInput)
                $signatureBytes    = $rsa.SignData(
                    $signingInputBytes,
                    [System.Security.Cryptography.HashAlgorithmName]::SHA256,
                    [System.Security.Cryptography.RSASignaturePadding]::Pkcs1
                )
                $signatureB64 = ConvertTo-Base64Url $signatureBytes
            } finally {
                $rsa.Dispose()
            }
        } catch {
            # Path B: host openssl fallback (requires openssl in PATH)
            if (Get-Command openssl -ErrorAction SilentlyContinue) {
                $tempInputFile = [System.IO.Path]::GetTempFileName()
                $tempSigFile   = [System.IO.Path]::GetTempFileName()
                try {
                    [System.IO.File]::WriteAllText($tempInputFile, $signingInput, [System.Text.Encoding]::UTF8)
                    $null = openssl dgst -sha256 -sign $absolutePrivateKeyPath -out $tempSigFile $tempInputFile 2>&1
                    if ($LASTEXITCODE -eq 0 -and (Test-Path $tempSigFile)) {
                        $signatureBytes = [System.IO.File]::ReadAllBytes($tempSigFile)
                        $signatureB64   = ConvertTo-Base64Url $signatureBytes
                    }
                } finally {
                    Remove-Item $tempInputFile, $tempSigFile -ErrorAction SilentlyContinue
                }
            }

            # Path C: docker fallback (runs openssl in alpine container)
            if (-not $signatureB64 -and (Get-Command docker -ErrorAction SilentlyContinue)) {
                $secretDirAbs = Split-Path $absolutePrivateKeyPath -Parent
                $privKeyFile  = Split-Path $absolutePrivateKeyPath -Leaf
                $sigOut = docker run --rm -v "${secretDirAbs}:/secrets:ro" alpine sh -c "apk add --no-cache openssl >/dev/null 2>&1; printf '%s' '$signingInput' | openssl dgst -sha256 -sign /secrets/${privKeyFile} 2>/dev/null | base64 | tr -d '\r\n' | tr '+/' '-_' | tr -d '='" 2>&1 | Out-String
                if ($LASTEXITCODE -eq 0 -and $sigOut.Trim()) {
                    $signatureB64 = $sigOut.Trim()
                }
            }
        }

        if (-not $signatureB64) {
            throw "Failed to sign Temporal service token - neither .NET, host openssl, nor docker openssl succeeded."
        }

        $token = "$signingInput.$signatureB64"

    [System.IO.File]::WriteAllText(
        $absoluteOutputPath,
        $token,
        [System.Text.UTF8Encoding]::new($false)
    )

    Write-Ok "Generated Temporal service token at $OutputPath ($days days valid)"
}

function Test-ServiceHttp {
    param([string]$Url, [int]$Timeout = 2)
    try { (Invoke-WebRequest -Uri $Url -UseBasicParsing -TimeoutSec $Timeout).StatusCode -eq 200 }
    catch { $false }
}

# -- Prerequisite: Docker running ---------------------------------------------

Write-Status "Checking Docker..."
$dockerOk = $false
try {
    $null = docker info 2>$null
    $dockerOk = $LASTEXITCODE -eq 0
} catch { }

if (-not $dockerOk) {
    Write-Err "Docker is not running. Start Docker Desktop and try again."
    exit 1
}

# -- Handle -Down -------------------------------------------------------------

if ($Down) {
    Write-Status "Stopping all containers..."
    $envArgs = if (Test-Path $EnvFile) { @("--env-file", $EnvFile) } else { @() }
    docker compose -f $ComposeFile @envArgs down
    Write-Ok "All containers stopped"
    exit 0
}

# -- Handle -Logs -------------------------------------------------------------

if ($Logs) {
    $envArgs = if (Test-Path $EnvFile) { @("--env-file", $EnvFile) } else { @() }
    if ($LogService) {
        docker compose -f $ComposeFile @envArgs logs -f $LogService
    } else {
        docker compose -f $ComposeFile @envArgs logs -f
    }
    exit 0
}

# -- Generate secrets ---------------------------------------------------------

$generated = $false

$needsEnvDocker = -not (Test-Path $EnvFile)
$needsEnvCompose = -not (Test-Path $EnvCompose)

if ($needsEnvDocker -and $needsEnvCompose) {
    # Both missing - fresh setup, generate from scratch
    Write-Status "Generating environment files with secure secrets..."

    $postgresPassword = New-Secret -Length 32
    $secretKey         = New-Secret -Length 64
    $minioPassword     = New-Secret -Length 24
    $redisPassword     = New-Secret -Length 24
    $elasticPassword   = New-Secret -Length 24
    $natsPassword      = New-Secret -Length 24
    $spicedbKey        = New-Secret -Length 32
    $wsHubSecret       = New-Secret -Length 32
    $grafanaPassword   = New-Secret -Length 24

    # -- .env.docker (container env_file) ---------------------------------
    $dockerEnv = @"
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=university
SECRET_KEY=$secretKey
ALGORITHM=RS256
JWT_PRIVATE_KEY_PATH=.secrets/jwt_rs256.pem
ACCESS_TOKEN_EXPIRE_MINUTES=30
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$minioPassword
ELASTIC_PASSWORD=$elasticPassword
NATS_USER=app
NATS_PASSWORD=$natsPassword
SPICEDB_PRESHARED_KEY=$spicedbKey
WS_HUB_INTERNAL_SECRET=$wsHubSecret
GRAFANA_ADMIN_PASSWORD=$grafanaPassword
REDIS_PASSWORD=$redisPassword
VAPID_SUBJECT=mailto:admin@example.com
ENVIRONMENT=development
SPOTIFY_CLIENT_ID=
SPOTIFY_CLIENT_SECRET=
SPOTIFY_REDIRECT_URI=
SPOTIFY_SCOPES=
"@
    Write-Utf8NoBom $EnvFile $dockerEnv

    # -- .env (compose interpolation) -------------------------------------
    $composeEnv = @"
# Auto-generated by start-docker.ps1 - used for docker compose interpolation.
# Passwords MUST match .env.docker. Re-run start-docker.ps1 after editing.
POSTGRES_USER=postgres
POSTGRES_PASSWORD=$postgresPassword
POSTGRES_DB=university
SECRET_KEY=$secretKey
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=$minioPassword
ELASTIC_PASSWORD=$elasticPassword
NATS_USER=app
NATS_PASSWORD=$natsPassword
SPICEDB_PRESHARED_KEY=$spicedbKey
WS_HUB_INTERNAL_SECRET=$wsHubSecret
GRAFANA_ADMIN_PASSWORD=$grafanaPassword
REDIS_PASSWORD=$redisPassword
ENVIRONMENT=development
VAPID_SUBJECT=mailto:admin@example.com
SPOTIFY_CLIENT_ID=
SPOTIFY_CLIENT_SECRET=
SPOTIFY_REDIRECT_URI=
SPOTIFY_SCOPES=
"@
    Write-Utf8NoBom $EnvCompose $composeEnv

    Write-Ok "Generated $EnvFile and $EnvCompose with secure secrets"
    $generated = $true
} elseif ($needsEnvDocker -and -not $needsEnvCompose) {
    # .env exists but .env.docker missing - copy .env as base for .env.docker
    Write-Warn ".env.docker missing - deriving from .env..."
    Copy-Item $EnvCompose $EnvFile
    Write-Ok "Created $EnvFile from $EnvCompose"
    $generated = $true
} elseif (-not $needsEnvDocker -and $needsEnvCompose) {
    # .env.docker exists but .env missing - derive .env from .env.docker
    Write-Warn ".env missing - deriving from .env.docker..."
    Copy-Item $EnvFile $EnvCompose
    Write-Ok "Created $EnvCompose from $EnvFile"
    $generated = $true
}

# -- Sync check: ensure .env has all required vars ----------------------------

if (-not $generated) {
    $envContent = Get-Content $EnvCompose -Raw -ErrorAction SilentlyContinue
    $missing = @()
    foreach ($key in @("WS_HUB_INTERNAL_SECRET", "REDIS_PASSWORD", "MINIO_ROOT_PASSWORD", "SPICEDB_PRESHARED_KEY", "GRAFANA_ADMIN_PASSWORD")) {
        if ($envContent -notmatch "(?m)^$key=") {
            $missing += $key
        }
    }
    if ($missing.Count -gt 0) {
        Write-Warn "Missing vars in .env: $($missing -join ', '). Reading from .env.docker..."
        $dockerLines = Get-Content $EnvFile -ErrorAction SilentlyContinue
        $patch = ""
        foreach ($key in $missing) {
            $line = $dockerLines | Where-Object { $_ -match "^$key=" } | Select-Object -First 1
            if ($line) { $patch += "`n$line" }
        }
        if ($patch) {
            Add-Content -Path $EnvCompose -Value $patch -NoNewline:$false
            Write-Ok "Patched .env with missing vars"
        }
    }
}

# -- Wave 137 SW1: Migrate existing .env.docker to RS256 ----------------------
# Pre-W137 .env.docker has ALGORITHM=HS256 (no JWT_PRIVATE_KEY_PATH).
# Post-W137 expects ALGORITHM=RS256 + JWT_PRIVATE_KEY_PATH=.secrets/jwt_rs256.pem.
# Auto-patch existing files for seamless upgrade.
if (Test-Path $EnvFile) {
    $envDockerContent = Get-Content $EnvFile -Raw -ErrorAction SilentlyContinue
    $needsAlgorithmFlip = $envDockerContent -match "(?m)^ALGORITHM=HS256\s*$"
    $needsKeyPath = $envDockerContent -notmatch "(?m)^JWT_PRIVATE_KEY_PATH="

    if ($needsAlgorithmFlip -or $needsKeyPath) {
        Write-Status "Migrating $EnvFile to RS256 (Wave 137 SW1)..."

        if ($needsAlgorithmFlip) {
            $envDockerContent = $envDockerContent -replace "(?m)^ALGORITHM=HS256\s*$", "ALGORITHM=RS256"
            Write-Ok "Flipped ALGORITHM=HS256 -> ALGORITHM=RS256"
        }

        if ($needsKeyPath) {
            # Insert JWT_PRIVATE_KEY_PATH after ALGORITHM line (or after SECRET_KEY if ALGORITHM missing)
            if ($envDockerContent -match "(?m)^ALGORITHM=") {
                $envDockerContent = $envDockerContent -replace `
                    "((?m)^ALGORITHM=[^\r\n]*)", `
                    "`$1`nJWT_PRIVATE_KEY_PATH=.secrets/jwt_rs256.pem"
            } else {
                $envDockerContent += "`nJWT_PRIVATE_KEY_PATH=.secrets/jwt_rs256.pem"
            }
            Write-Ok "Added JWT_PRIVATE_KEY_PATH=.secrets/jwt_rs256.pem"
        }

        Write-Utf8NoBom $EnvFile $envDockerContent.TrimEnd()
    }
}

# -- Wave 137 SW1: Generate RSA-2048 keypair for JWT RS256 signing -------------
# Backend reads .secrets/jwt_rs256.pem at startup (jwt_settings.py:202-205).
# Volume-mounted into container at /app/.secrets/jwt_rs256.pem.
New-JwtRs256Key -OutputPath ".secrets/jwt_rs256.pem"

# -- Wave 142 SW3: Derive RSA-2048 public key for Temporal JWT verification ---
# Temporal reads .secrets/jwt_rs256.pub.pem via TEMPORAL_JWT_KEY_SOURCE1=
# file:///app/.secrets/jwt_rs256.pub.pem env var (rendered into config.yaml
# by auto-setup's config_template.yaml line 260). The file:// approach avoids
# the HTTP JWKS chicken-and-egg with backend startup ordering - W141 SW3
# tried http://backend:8000/.well-known/jwks.json and likely contributed to
# the (z) cascade. Public key is derived from the same RSA-2048 private key
# the backend uses to sign JWTs (.secrets/jwt_rs256.pem from W137 SW1).
New-JwtRs256PublicKey -PrivateKeyPath ".secrets/jwt_rs256.pem" -OutputPath ".secrets/jwt_rs256.pub.pem"

# -- Wave 141 SW4: Mint Temporal service token (RS256 JWT) ---------------------
# file-processor (W141 SW5) reads .secrets/temporal_api_key and attaches it to
# Temporal client via client.NewAPIKeyStaticCredentials(token). Temporal's
# default JWT claim mapper (W141 SW2 verified) validates via the JWKS endpoint
# at /.well-known/jwks.json. Idempotent - skips if file exists.
New-TemporalServiceToken

# -- Wave 137 SW2: SECRET_KEY drift detection .env <-> .env.docker ---------------
# Closes W136 polish-v2 finding: gateway's JWT_SECRET env reads from .env via
# compose's ${SECRET_KEY} substitution, while backend's env_file reads .env.docker.
# If .env's SECRET_KEY drifts (e.g. stale Pydantic placeholder), gateway HS256
# fallback path validates against the wrong secret -> 401 on every request.
# Less critical post-W137 SW1 RS256 (gateway uses JWKS path) but kept for
# defense-in-depth: fallback HS256 path must remain coherent.
if ((Test-Path $EnvFile) -and (Test-Path $EnvCompose)) {
    $envDockerSecret = (Select-String -Path $EnvFile -Pattern "^SECRET_KEY=(.+)$" -ErrorAction SilentlyContinue).Matches.Groups[1].Value
    $envComposeSecret = (Select-String -Path $EnvCompose -Pattern "^SECRET_KEY=(.+)$" -ErrorAction SilentlyContinue).Matches.Groups[1].Value

    if ($envDockerSecret -and $envComposeSecret -and $envDockerSecret -ne $envComposeSecret) {
        Write-Warn "SECRET_KEY drift detected between .env and .env.docker"
        Write-Status "Syncing .env SECRET_KEY to match .env.docker (canonical source)..."

        # Line-based replacement avoids regex special-char hazards in the
        # secret value (which is alphanumeric per New-Secret but defensive).
        $newLine = "SECRET_KEY=$envDockerSecret"
        $envComposeContent = (Get-Content $EnvCompose -ErrorAction SilentlyContinue | ForEach-Object {
            if ($_ -match "^SECRET_KEY=") { $newLine } else { $_ }
        }) -join "`n"

        Write-Utf8NoBom $EnvCompose $envComposeContent.TrimEnd()
        Write-Ok "Synced .env SECRET_KEY (defense-in-depth for HS256 fallback path)"
    }
}

# -- Build --------------------------------------------------------------------

if ($Rebuild) {
    Write-Status "Rebuilding ALL images (no cache)..."
    docker compose -f $ComposeFile --env-file $EnvFile build --no-cache
    if ($LASTEXITCODE -ne 0) {
        Write-Err "Build failed. Check output above."
        exit 1
    }
    Write-Ok "All images rebuilt"
} elseif ($Build) {
    Write-Status "Building images (cached)..."
    docker compose -f $ComposeFile --env-file $EnvFile build
    if ($LASTEXITCODE -ne 0) {
        Write-Err "Build failed. Check output above."
        exit 1
    }
    Write-Ok "Images built"
}

# -- Start services -----------------------------------------------------------

Write-Status "Starting containers..."
docker compose -f $ComposeFile --env-file $EnvFile up -d
if ($LASTEXITCODE -ne 0) {
    Write-Err "Failed to start containers."
    exit 1
}

# -- First-run initialization -------------------------------------------------

# SpiceDB needs its own database in Postgres (idempotent)
Write-Status "Ensuring SpiceDB database exists..."
& {
    $ErrorActionPreference = "SilentlyContinue"
    docker compose -f $ComposeFile --env-file $EnvFile exec -T postgres psql -U postgres -c "CREATE DATABASE spicedb" 2>$null
}
# Ignore errors - database may already exist

# SpiceDB needs migrations after fresh DB creation
Write-Status "Running SpiceDB migrations..."
$pgPass = (Select-String -Path $EnvFile -Pattern "^POSTGRES_PASSWORD=(.+)$").Matches.Groups[1].Value
$projectName = (Split-Path $ProjectRoot -Leaf).ToLower() -replace '[^a-z0-9]', '_'
$network = "${projectName}_internal"
& {
    $ErrorActionPreference = "SilentlyContinue"
    docker run --rm --network $network authzed/spicedb:v1.51.0 migrate head --datastore-engine postgres --datastore-conn-uri "postgres://postgres:${pgPass}@postgres:5432/spicedb?sslmode=disable" 2>$null
}
if ($LASTEXITCODE -eq 0) {
    Write-Ok "SpiceDB migrations applied"
} else {
    Write-Warn "SpiceDB migration failed or already up-to-date"
}

# MinIO bucket (wait for MinIO to be healthy, then create via minio/mc container)
Write-Status "Ensuring MinIO 'uploads' bucket exists..."
$minioReady = $false
for ($i = 0; $i -lt 12; $i++) {
    $healthStr = & { $ErrorActionPreference = "SilentlyContinue"; docker compose -f $ComposeFile --env-file $EnvFile ps minio --format json 2>$null } | Out-String
    $health = if ($healthStr -match "\{") { $healthStr | ConvertFrom-Json } else { $null }
    $h = if ($health -is [array]) { $health[0].Health } else { $health.Health }
    if ($h -eq "healthy") { $minioReady = $true; break }
    Start-Sleep -Seconds 5
}
if ($minioReady) {
    $minioPass = (Select-String -Path $EnvFile -Pattern "^MINIO_ROOT_PASSWORD=(.+)$").Matches.Groups[1].Value
    # mc is NOT in minio/minio image - use separate minio/mc container on the same network
    $projectName = (Split-Path $ProjectRoot -Leaf).ToLower() -replace '[^a-z0-9]', '_'
    $network = "${projectName}_internal"
    & {
        $ErrorActionPreference = "SilentlyContinue"
        docker run --rm --network $network --entrypoint "" minio/mc sh -c "mc alias set local http://minio:9000 minioadmin $minioPass && mc mb local/uploads --ignore-existing" 2>$null
    }
    if ($LASTEXITCODE -eq 0) {
        Write-Ok "MinIO bucket ready"
    } else {
        Write-Warn "Could not create MinIO bucket - create manually after startup"
    }
} else {
    Write-Warn "MinIO not healthy yet - create bucket manually after startup"
}

# -- Health check loop --------------------------------------------------------

Write-Status "Waiting for services..."
$timeout = 120
$elapsed = 0
$services = @{
    postgres = @{ type = "docker"; ready = $false }
    backend  = @{ type = "docker"; ready = $false }
    nats     = @{ type = "docker"; ready = $false }
    gateway  = @{ type = "http"; url = "http://localhost:8080/health"; ready = $false }
    wshub    = @{ type = "http"; url = "http://localhost:8083/health"; ready = $false }
    frontend = @{ type = "http"; url = "http://localhost:8081/healthz"; ready = $false }
    caddy    = @{ type = "http"; url = "http://localhost/healthz"; ready = $false }
}

do {
    Start-Sleep -Seconds 5
    $elapsed += 5

    foreach ($name in $services.Keys) {
        if ($services[$name].ready) { continue }

        if ($services[$name].type -eq "docker") {
            $infoStr = & { $ErrorActionPreference = "SilentlyContinue"; docker compose -f $ComposeFile --env-file $EnvFile ps $name --format json 2>$null } | Out-String
            $info = if ($infoStr -match "\{") { $infoStr | ConvertFrom-Json } else { $null }
            $h = if ($info -is [array]) { $info[0].Health } else { $info.Health }
            if ($h -eq "healthy") { $services[$name].ready = $true }
        } else {
            if (Test-ServiceHttp $services[$name].url) { $services[$name].ready = $true }
        }
    }

    # Status line
    $statParts = @()
    foreach ($name in @("postgres", "backend", "gateway", "caddy", "frontend", "nats", "wshub")) {
        $icon = if ($services[$name].ready) { "+" } else { "." }
        $color = if ($services[$name].ready) { "Green" } else { "DarkGray" }
        $statParts += @{ name = $name; icon = $icon; color = $color }
    }
    Write-Host -NoNewline "  "
    foreach ($p in $statParts) {
        Write-Host -NoNewline "[$($p.icon)] $($p.name)  " -ForegroundColor $p.color
    }
    Write-Host ""  # newline

    $allReady = ($services.Values | Where-Object { -not $_.ready }).Count -eq 0

} while (-not $allReady -and $elapsed -lt $timeout)

if (-not $allReady) {
    Write-Err "Timeout after ${timeout}s. Failing services:"
    foreach ($name in $services.Keys) {
        if (-not $services[$name].ready) {
            Write-Err "  $name - showing last 15 log lines:"
            docker compose -f $ComposeFile --env-file $EnvFile logs --tail=15 $name 2>$null
            Write-Host ""
        }
    }
    exit 1
}

# -- Done ---------------------------------------------------------------------

Write-Host ""
Write-Ok "University Ecosystem is running!"
Write-Host ""
Write-Host "  >> Site (use this):  http://localhost/" -ForegroundColor Green
Write-Host "     Caddy reverse proxy routes /api/* -> gateway:8080 -> backend:8000," -ForegroundColor DarkGray
Write-Host "     /ws/* -> ws-hub:8081, /sw.js -> frontend:3000, default -> frontend:3000." -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Direct service ports (admin/debug only - browser API calls won't work)" -ForegroundColor Gray
Write-Host "  Frontend (Node SSR):  http://localhost:8081  (no /api proxy - use http://localhost/)" -ForegroundColor DarkYellow
Write-Host "  Gateway API:          http://localhost:8080" -ForegroundColor DarkYellow
Write-Host "  Backend API:          http://localhost:8000  (127.0.0.1 only)" -ForegroundColor DarkYellow
Write-Host "  API Docs:             http://localhost:8000/docs" -ForegroundColor DarkYellow
Write-Host "  WS Hub:               http://localhost:8083" -ForegroundColor DarkYellow
Write-Host "  MinIO Console:        http://localhost:9001" -ForegroundColor DarkYellow
Write-Host "  Grafana:              http://localhost:3000" -ForegroundColor DarkYellow
Write-Host ""
Write-Host "Seed data:" -ForegroundColor Cyan
Write-Host "  1) Demo content (idempotent - student user + news + events + schedule + stories):"
Write-Host "       docker exec -w /app university_ecosystem-backend-1 python scripts/seed_demo_data.py"
Write-Host "       Login: test@university.dev / TestPass@2024x"
Write-Host "  2) Admin content (idempotent - admin user + 6 users + 12 audit logs + 4 dead-letter jobs):"
Write-Host "       docker cp scripts/seed_admin_data.py university_ecosystem-backend-1:/app/seed_admin_data.py"
Write-Host "       docker exec -w /app university_ecosystem-backend-1 python seed_admin_data.py"
Write-Host "       Login: admin@university.dev / Admin@2024test"
Write-Host ""
Write-Host "Commands:" -ForegroundColor Gray
Write-Host "  Stop:      .\start-docker.ps1 -Down"
Write-Host "  Logs:      .\start-docker.ps1 -Logs"
Write-Host "  Logs svc:  .\start-docker.ps1 -Logs -LogService backend"
Write-Host "  Build:     .\start-docker.ps1 -Build"
Write-Host "  Rebuild:   .\start-docker.ps1 -Rebuild   (no cache)"
