[package]
name = "rust_ext-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { version = "1", features = ["derive"] }
libfuzzer-sys = "0.4"
rust_ext = { path = "..", default-features = false }

[[bin]]
name = "fuzz_hmac"
path = "fuzz_targets/fuzz_hmac.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_conflict_detection"
path = "fuzz_targets/fuzz_conflict_detection.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_schedule_item"
path = "fuzz_targets/fuzz_schedule_item.rs"
test = false
doc = false
bench = false
