[package]
name = "rust_ext-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
ammonia = "4.1.2"
chrono = { version = "0.4", features = ["serde"] }
libfuzzer-sys = "0.4"

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_sanitizer"
path = "fuzz_targets/fuzz_sanitizer.rs"
test = false
doc = false
bench = false
