"""Keep every Knip exception tied to a concrete frontend tool or generated file.

The exceptions are deliberately exact: browser-loaded axe-core, command-line
tools invoked through config strings, generated outputs, and platform
binaries. Knip follows CSS and MDX imports, so Tailwind and the trusted-types
declarations need no exception. Vitest source tests and handwritten MSW
fixtures stay in Knip's graph so new unused code is still reported.
"""

from __future__ import annotations

import fnmatch
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FRONTEND = ROOT / "frontend"


def _read_frontend(relative_path: str) -> str:
    return (FRONTEND / relative_path).read_text(encoding="utf-8")


def test_vitest_source_tests_and_setup_keep_fixture_handlers_discoverable() -> None:
    knip = json.loads((FRONTEND / "knip.json").read_text(encoding="utf-8"))

    # Only globs that match real files: Knip reports unmatched entries as
    # configuration hints, and treatConfigHintsAsErrors makes those fatal.
    source_test_globs = ["src/**/*.test.ts", "src/**/*.test.tsx"]
    assert all(pattern in knip["entry"] for pattern in source_test_globs)
    assert not any(".spec." in pattern for pattern in knip["entry"])
    assert "wasm-sanitizer/tests/**/*.js" in knip["entry"]
    assert "src/**/*.{ts,tsx,css,mdx}" in knip["project"]

    # Vitest loads setupTests before every source test (Knip's Vitest plugin
    # adds it as an entry). That setup imports the handwritten handlers, which
    # in turn keeps their fixture graph visible.
    setup = _read_frontend("src/setupTests.ts")
    handlers = "src/tests/mocks/handlers.ts"
    assert 'setupFiles: ["src/setupTests.ts"]' in _read_frontend("vitest.config.ts")
    assert 'from "./tests/mocks/handlers"' in setup
    assert (FRONTEND / handlers).is_file()
    assert not any(fnmatch.fnmatchcase(handlers, pattern) for pattern in knip["ignore"])
    assert not any(
        fnmatch.fnmatchcase(handlers, pattern)
        for pattern in knip.get("ignoreIssues", {})
    )


def test_each_file_ignore_is_exact_and_points_to_generated_output() -> None:
    package = json.loads((FRONTEND / "package.json").read_text(encoding="utf-8"))
    knip = json.loads((FRONTEND / "knip.json").read_text(encoding="utf-8"))
    expected_ignored_paths = [
        "src/api/generated/**",
        "src/tests/mocks/generated/**",
    ]

    assert knip["ignore"] == expected_ignored_paths
    assert "openapi-ts" in package["scripts"]["generate:api"]
    assert "src/tests/mocks/generated" in package["scripts"]["generate:api"]
    assert "auto-generated by @hey-api/openapi-ts" in _read_frontend(
        "src/api/generated/index.ts"
    )
    assert "AUTO GENERATED by [msw-auto-mock]" in _read_frontend(
        "src/tests/mocks/generated/handlers.ts"
    )
    # src/routeTree.gen.ts needs no ignore: Knip's TanStack plugin follows it.


def test_generated_theme_tokens_ignore_only_path_scoped_export_issues() -> None:
    knip = json.loads((FRONTEND / "knip.json").read_text(encoding="utf-8"))

    assert knip["ignoreIssues"] == {"src/theme/tokens.ts": ["exports"]}
    assert (FRONTEND / "src/theme/tokens.ts").is_file()
    assert 'path.resolve(__dirname, "../src/theme/tokens.ts")' in _read_frontend(
        "scripts/sync-tokens.mjs"
    )


def test_dependency_ignores_are_limited_to_known_required_dependencies() -> None:
    package = json.loads((FRONTEND / "package.json").read_text(encoding="utf-8"))
    knip = json.loads((FRONTEND / "knip.json").read_text(encoding="utf-8"))
    expected_ignored_dependencies = [
        "@lhci/cli",
        "^@stryker-mutator/\\*$",
        "axe-core",
        "cross-env",
        "openapi-types",
    ]
    asset_users = {
        "scripts/authenticated-visual-audit.mjs",
        "tests/e2e/a11y-enhanced.spec.ts",
        "tests/e2e/a11y-messenger.spec.ts",
        "tests/e2e/a11y-cdn-axe.spec.ts",
        "tests/e2e/accessibility.spec.ts",
        "tests/e2e/a11y-public.spec.ts",
        "tests/e2e/schedule-view.spec.ts",
        "tests/e2e/visual-regression.spec.ts",
    }

    assert knip["ignoreDependencies"] == expected_ignored_dependencies
    declared_ignored_dependencies = {
        dependency
        for dependency in expected_ignored_dependencies
        if dependency != "^@stryker-mutator/\\*$"
    }
    assert declared_ignored_dependencies <= set(package["devDependencies"])

    # The dependency is declared to satisfy swagger-parser's required peer,
    # which msw-auto-mock loads for its OpenAPI generation command.
    lock_packages = json.loads(
        (FRONTEND / "package-lock.json").read_text(encoding="utf-8")
    )["packages"]
    msw_auto_mock = lock_packages["node_modules/msw-auto-mock"]
    swagger_parser = lock_packages["node_modules/@apidevtools/swagger-parser"]
    assert msw_auto_mock["dependencies"]["@apidevtools/swagger-parser"]
    assert swagger_parser["peerDependencies"]["openapi-types"] == ">=7"
    assert "openapi-types" not in swagger_parser.get("peerDependenciesMeta", {})

    # Stryker loads the package namespace dynamically, so Knip sees its glob
    # as an unresolved dependency string. The exact escaped-star ignore above
    # matches only that one config token.
    assert '"@stryker-mutator/*"' in _read_frontend("stryker.config.mjs")

    # Knip cannot follow this local browser asset load as npm package usage.
    actual_asset_users = {
        path.relative_to(FRONTEND).as_posix()
        for root in (FRONTEND / "scripts", FRONTEND / "tests")
        for path in root.rglob("*")
        if path.is_file()
        and path.suffix in {".js", ".mjs", ".ts", ".tsx"}
        and "node_modules/axe-core/axe.min.js" in path.read_text(encoding="utf-8")
    }
    assert actual_asset_users == asset_users

    # These uses need explicit package accounting: the LHCI CLI and cross-env
    # appear in command strings. Tailwind (a CSS @import) and the trusted-types
    # declarations (DefinitelyTyped's @types package) are found by Knip itself.
    assert (
        'process.platform === "win32" ? ["exec", "--yes", "lhci", "--"] : ["lhci"]'
        in (_read_frontend("scripts/run-lhci.mjs"))
    )
    assert 'from "trusted-types/lib"' in _read_frontend("src/utils/trustedTypes.ts")
    assert 'from "trusted-types/lib"' in _read_frontend("src/utils/sanitize.ts")
    assert "npx cross-env" in _read_frontend("playwright.config.ts")
    assert '@import "tailwindcss";' in _read_frontend("src/styles/tailwind.css")


def test_ignored_binaries_are_exact_and_have_authored_call_sites() -> None:
    knip = json.loads((FRONTEND / "knip.json").read_text(encoding="utf-8"))

    assert knip["ignoreBinaries"] == ["taskkill.exe", "mkfifo", "uv"]
    assert 'spawn("taskkill.exe"' in _read_frontend("scripts/build-orchestrated.mjs")
    assert 'execFileSync("mkfifo"' in _read_frontend(
        "scripts/stryker-progress-monitor.test.mjs"
    )
    assert 'spawnSync("uv"' in _read_frontend(
        "wasm-sanitizer/tests/wasm_sanitizer_node_test.js"
    )
