"""Tests to validate that OpenAPI links are successfully injected and parsed.

Uses Schemathesis to load the ASGI application schema and assert structural correctness
of the links.
"""

from __future__ import annotations

import os

import pytest
import schemathesis
from fastapi.testclient import TestClient

# Prevent any loopback address parsing issue in httpx if it leaks
for proxy_key in ["no_proxy", "NO_PROXY"]:
    if proxy_key in os.environ:
        os.environ[proxy_key] = ",".join(
            item for item in os.environ[proxy_key].split(",") if ":" not in item
        )

from app.main import app


@pytest.fixture(autouse=True)
def force_openapi_url():
    """Temporarily enable openapi_url in testing environment to allow downloads."""
    old_url = app.openapi_url
    app.openapi_url = "/api/openapi.json"
    yield
    app.openapi_url = old_url


def test_openapi_schema_contains_links() -> None:
    """Validate that custom OpenAPI links exist in the autogenerated schema."""
    with TestClient(app) as client:
        response = client.get("/api/openapi.json")
        assert response.status_code == 200
        schema = response.json()

        paths = schema.get("paths", {})

        # 1. Login links to get_me
        login_post = paths.get("/api/v1/auth/login", {}).get("post", {})
        login_links = login_post.get("responses", {}).get("200", {}).get("links", {})
        assert "GetCurrentUser" in login_links
        assert (
            login_links["GetCurrentUser"]["operationId"] == "get_me_api_v1_users_me_get"
        )

        # 2. Create event links to get_event
        create_event = paths.get("/api/v1/events", {}).get("post", {})
        event_links = create_event.get("responses", {}).get("200", {}).get("links", {})
        assert "GetEventById" in event_links
        assert (
            event_links["GetEventById"]["operationId"]
            == "get_event_api_v1_events__event_id__get"
        )
        assert (
            event_links["GetEventById"]["parameters"]["event_id"]
            == "$response.body#/id"
        )

        # 3. Create chat links to get_messages
        create_chat = paths.get("/api/v1/chats", {}).get("post", {})
        chat_links = create_chat.get("responses", {}).get("200", {}).get("links", {})
        assert "GetChatMessages" in chat_links
        assert (
            chat_links["GetChatMessages"]["operationId"]
            == "get_messages_api_v1_chats__chat_id__messages_get"
        )
        assert (
            chat_links["GetChatMessages"]["parameters"]["chat_id"]
            == "$response.body#/id"
        )


def test_schemathesis_parses_openapi_with_links() -> None:
    """Validate that Schemathesis can successfully parse the schema with links."""
    # Ensure openapi schema is built
    schema_dict = app.openapi()
    schema = schemathesis.openapi.from_dict(schema_dict)

    # Verify that the links are recognized by schemathesis parsing
    login_op = schema["/api/v1/auth/login"]["POST"]
    assert "GetCurrentUser" in login_op.definition.raw["responses"]["200"]["links"]

    create_event_op = schema["/api/v1/events"]["POST"]
    assert "GetEventById" in create_event_op.definition.raw["responses"]["200"]["links"]
