"""Wave 2 / Task 2.3 — Schemathesis v4 property-based OpenAPI conformance tests.

Schemathesis generates random-but-valid HTTP requests directly from the live
FastAPI OpenAPI schema and asserts that every response conforms to the declared
schema — correct status codes, response body shapes, and content types.

Architecture
------------
Uses ``schemathesis.openapi.from_asgi`` with the FastAPI ASGI app directly
(available in schemathesis >=4.0 with the TestClient transport).  No network
or server process required — fully hermetic.

Schema loading is lazy via ``schemathesis.pytest.from_fixture``:

    _lazy_schema = schemathesis.pytest.from_fixture("loaded_schema")

This creates a ``LazySchema`` that stores the fixture name as a string at
module parse/collection time.  The actual ``from_asgi()`` ASGI round-trip only
happens at test *execution* time (via ``request.getfixturevalue("loaded_schema")``
inside the wrapped test), never during pytest collection.  This prevents the
app lifespan from blocking collection when backing services are unavailable.

The ``@_lazy_schema.parametrize()`` decorator is intercepted by the schemathesis
pytest plugin which parametrizes the test over every (method, path) pair and
runs a Hypothesis test for each one.

What this catches
-----------------
- Response body missing a declared required field
- Incorrect status code returned (e.g. 200 instead of 201)
- Content-Type header mismatch
- Endpoints that crash with 500 on any valid input shape
- Schema drift between the FastAPI route definition and its actual response

Run locally
-----------
    uv run pytest tests/test_schemathesis_api.py -v
"""

from __future__ import annotations

import json
import os

import hypothesis
import pytest
import schemathesis

# ---------------------------------------------------------------------------
# Custom Schemathesis Conformance Check
# ---------------------------------------------------------------------------
import schemathesis.checks
from hypothesis import HealthCheck
from schemathesis.checks import not_a_server_error

schemathesis.checks.load_all_checks()


@schemathesis.check
def conform_to_schema_except_auth(ctx, response, case) -> None:
    """Validate that the response conforms to the OpenAPI specification.

    If the response is a 401, 403, or 404, we skip schema validation.
    401/403 are skipped because the run is stateless and unauthenticated,
    and 404 is skipped because random IDs generated by Schemathesis will not exist.

    For all other status codes, this check enforces:
    - No 5xx server errors
    - Status code matches what is declared in the spec
    - Content-Type matches what is declared in the spec
    - Response body conforms to the schema in the spec
    """
    if response.status_code in (401, 403, 404):
        return

    from schemathesis.checks import (
        content_type_conformance,
        response_schema_conformance,
        status_code_conformance,
    )

    not_a_server_error(ctx, response, case)
    status_code_conformance(ctx, response, case)
    content_type_conformance(ctx, response, case)
    response_schema_conformance(ctx, response, case)


# ---------------------------------------------------------------------------
# Environment setup — must precede any app import
# ---------------------------------------------------------------------------

os.environ.setdefault("DATABASE_URL", "sqlite+aiosqlite:///./test_schemathesis.db")
os.environ.setdefault("ENVIRONMENT", "testing")
os.environ.setdefault(
    "SECRET_KEY",
    "schemathesis-ci-placeholder-secret-key-minimum-32-chars-long",  # pragma: allowlist secret
)

from app.main import app  # env vars must be set before this import

# ---------------------------------------------------------------------------
# Schema loader — evaluated at module parse time but the ASGI call is deferred.
#
# ``schemathesis.pytest.from_fixture("loaded_schema")`` returns a ``LazySchema``
# that stores the fixture name as a plain string.  No ASGI round-trip happens
# here.  The real ``schemathesis.openapi.from_asgi()`` call only occurs inside
# the test body (via ``request.getfixturevalue("loaded_schema")``), so a slow
# or missing backing service cannot hang pytest collection.
# ---------------------------------------------------------------------------

_lazy_schema = schemathesis.pytest.from_fixture("loaded_schema")


@pytest.fixture(scope="session")
def loaded_schema():
    """Return the schemathesis schema loaded from the ASGI app.

    Session-scoped so the ASGI round-trip (fetching /api/openapi.json) happens
    exactly once per pytest session, not once per test case.
    """
    return schemathesis.openapi.from_asgi("/api/openapi.json", app=app)


# ---------------------------------------------------------------------------
# Stateless property-based conformance tests
#
# Decorator order matters for Hypothesis settings to take effect with a
# LazySchema: @hypothesis.settings must be the OUTER decorator so that it sets
# ``_hypothesis_internal_use_settings`` on the function that
# ``LazySchema.parametrize()`` returned (and that schemathesis reads back at
# test run time via ``getattr(wrapped_test, "_hypothesis_internal_use_settings",
# None)``).
# ---------------------------------------------------------------------------


@hypothesis.settings(
    max_examples=25,
    suppress_health_check=[HealthCheck.too_slow, HealthCheck.filter_too_much],
)
@_lazy_schema.parametrize()
def test_api_responses_conform_to_schema(case: schemathesis.Case) -> None:
    """Every OpenAPI-described endpoint must return a non-5xx response and conform to spec.

    Schemathesis generates random valid requests for every (method, path)
    combination in the spec.  Auth-required endpoints may return 401/403
    (which are schema-declared), but NEVER 500.

    Checks applied:
      Custom conformance check that enforces status code, content-type,
      response schema, and no-server-errors for all non-auth responses.

    The schemathesis pytest plugin parametrizes this test once per (method,
    path) pair, reporting each failure with its exact endpoint.
    """
    response = case.call()
    case.validate_response(response, checks=[conform_to_schema_except_auth])


# ---------------------------------------------------------------------------
# Spec integrity smoke tests
# ---------------------------------------------------------------------------


def test_openapi_spec_declares_paths() -> None:
    """The live FastAPI app's OpenAPI spec must declare at least one path.

    A zero-path spec indicates the app failed to initialise its routing
    correctly (e.g. no routers included) and Schemathesis would produce
    no tests — a false-positive silence we must explicitly guard against.
    """
    spec = app.openapi()
    assert "paths" in spec, "OpenAPI spec must have a 'paths' section"
    assert len(spec["paths"]) >= 1, (
        f"Expected at least 1 declared path, got {len(spec['paths'])}. "
        "Ensure all FastAPI routers are included in app/main.py."
    )


def test_openapi_spec_is_valid_json() -> None:
    """The OpenAPI spec exported by FastAPI must be round-trip JSON-serialisable."""
    spec = app.openapi()
    serialised = json.dumps(spec)
    parsed = json.loads(serialised)
    assert parsed["openapi"].startswith("3."), "Spec must declare OpenAPI 3.x"
