"""Backwards-compatible aggregate of the generated API schemas.

The schemas themselves live in the domain modules imported below.  This
module stays because 75 call sites import from it, 56 of them through the
``from app.schemas import schemas`` module-object form, and because the
OpenAPI contract is generated from these names.
"""

from __future__ import annotations

from app.schemas.admin import (
    AuditLogListOut,
    AuditLogOut,
    FeatureFlagOut,
    TimeTravelResponse,
)
from app.schemas.common import (
    BaseModel,
    OrmModel,
)
from app.schemas.events import (
    EventAttendanceCreate,
    EventAttendanceOut,
    EventCreate,
    EventFileOut,
    EventOut,
    EventUpdate,
    PaginatedEvents,
)
from app.schemas.groups import (
    GroupCreate,
    GroupOut,
    GroupUpdate,
)
from app.schemas.identity import (
    ActiveSessionOut,
    EmailChangeTokenCreate,
    ForgotPasswordIn,
    MfaChallengeOut,
    MfaFactorStatusOut,
    MfaTotpEnrollmentOut,
    PasswordChangeOut,
    PasswordResetTokenCreate,
    RecoveryCodesGenerateOut,
    RecoveryCodeVerifyIn,
    ResetPasswordIn,
    SessionBulkRevokeOut,
    SessionSigningKeyOut,
    Token,
    UserEmailChangeIn,
    UserEmailConfirmIn,
    UserMfaMethodsOut,
    UserPasswordChangeIn,
)
from app.schemas.integrations import (
    SpotifyAuthURL,
    SpotifyNowPlayingOut,
)
from app.schemas.news import (
    NewsCommentCreate,
    NewsCommentOut,
    NewsCommentUpdate,
    NewsCreate,
    NewsInteractionsOut,
    NewsOut,
    NewsUpdate,
    PaginatedNews,
)
from app.schemas.notification_delivery import (
    NotificationCreate,
    NotificationDeadLetterJobOut,
    NotificationDeadLetterListOut,
    NotificationDeadLetterMutationOut,
    NotificationDeadLetterPurgeIn,
    NotificationDeadLetterReplayIn,
    NotificationMarkReadIn,
    NotificationOut,
    NotificationsListOut,
)
from app.schemas.schedule import (
    ScheduleBase,
    ScheduleCreate,
    ScheduleOut,
    ScheduleUpdate,
)
from app.schemas.stories import (
    StoryCreate,
    StoryOut,
    StoryUpdate,
)
from app.schemas.users import (
    DataDeletionOut,
    DataDeletionRequest,
    DataExportOut,
    TokenWithProfile,
    UserAdminUpdate,
    UserBase,
    UserCreate,
    UserEducationBase,
    UserOut,
    UserPreferencesBase,
    UserProfileBase,
    UserProfileFullFlattened,
    UserProfilePublicFlattened,
    UserProfileUpdate,
    UserPublicOut,
    UserSearchFilter,
)

__all__ = [
    "ActiveSessionOut",
    "AuditLogListOut",
    "AuditLogOut",
    "BaseModel",
    "DataDeletionOut",
    "DataDeletionRequest",
    "DataExportOut",
    "EmailChangeTokenCreate",
    "EventAttendanceCreate",
    "EventAttendanceOut",
    "EventCreate",
    "EventFileOut",
    "EventOut",
    "EventUpdate",
    "FeatureFlagOut",
    "ForgotPasswordIn",
    "GroupCreate",
    "GroupOut",
    "GroupUpdate",
    "MfaChallengeOut",
    "MfaFactorStatusOut",
    "MfaTotpEnrollmentOut",
    "NewsCommentCreate",
    "NewsCommentOut",
    "NewsCommentUpdate",
    "NewsCreate",
    "NewsInteractionsOut",
    "NewsOut",
    "NewsUpdate",
    "NotificationCreate",
    "NotificationDeadLetterJobOut",
    "NotificationDeadLetterListOut",
    "NotificationDeadLetterMutationOut",
    "NotificationDeadLetterPurgeIn",
    "NotificationDeadLetterReplayIn",
    "NotificationMarkReadIn",
    "NotificationOut",
    "NotificationsListOut",
    "OrmModel",
    "PaginatedEvents",
    "PaginatedNews",
    "PasswordChangeOut",
    "PasswordResetTokenCreate",
    "RecoveryCodeVerifyIn",
    "RecoveryCodesGenerateOut",
    "ResetPasswordIn",
    "ScheduleBase",
    "ScheduleCreate",
    "ScheduleOut",
    "ScheduleUpdate",
    "SessionBulkRevokeOut",
    "SessionSigningKeyOut",
    "SpotifyAuthURL",
    "SpotifyNowPlayingOut",
    "StoryCreate",
    "StoryOut",
    "StoryUpdate",
    "TimeTravelResponse",
    "Token",
    "TokenWithProfile",
    "UserAdminUpdate",
    "UserBase",
    "UserCreate",
    "UserEducationBase",
    "UserEmailChangeIn",
    "UserEmailConfirmIn",
    "UserMfaMethodsOut",
    "UserOut",
    "UserPasswordChangeIn",
    "UserPreferencesBase",
    "UserProfileBase",
    "UserProfileFullFlattened",
    "UserProfilePublicFlattened",
    "UserProfileUpdate",
    "UserPublicOut",
    "UserSearchFilter",
]
