apiVersion: v1
kind: Namespace
metadata:
  name: university-ecosystem
  labels:
    app.kubernetes.io/name: university-ecosystem
    app.kubernetes.io/managed-by: kubectl
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
