"""fix_missing_tables

Revision ID: 148642dd1207
Revises: f7aa476e968a
Create Date: 2026-01-18 22:30:50.324424

"""

from collections.abc import Sequence
from contextlib import contextmanager

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.utils.encryption
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "148642dd1207"
down_revision: str | None = "f7aa476e968a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


SKIPPED_TABLES = set()


def safe_create_table(table_name: str, *args, **kwargs) -> None:
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if not inspector.has_table(table_name):
        op.create_table(table_name, *args, **kwargs)
    else:
        SKIPPED_TABLES.add(table_name)


class DummyBatchOp:
    def __getattr__(self, name):
        return lambda *args, **kwargs: None


@contextmanager
def safe_batch_alter_table(table_name: str, schema=None, **kwargs):
    if table_name in SKIPPED_TABLES:
        yield DummyBatchOp()
    else:
        with op.batch_alter_table(table_name, schema=schema, **kwargs) as batch_op:
            yield batch_op


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgresql = bind.dialect.name == "postgresql"
    inspector = sa.inspect(bind)
    existing_columns = {c["name"] for c in inspector.get_columns("groups")}
    existing_indexes = {i["name"] for i in inspector.get_indexes("groups")}

    with safe_batch_alter_table("groups", schema=None) as batch_op:
        if "course" not in existing_columns:
            batch_op.add_column(sa.Column("course", sa.Integer(), nullable=True))
        if "faculty" not in existing_columns:
            batch_op.add_column(sa.Column("faculty", sa.String(), nullable=True))
        batch_op.alter_column(
            "id",
            existing_type=sa.VARCHAR(length=20),
            type_=sa.Integer(),
            existing_nullable=False,
            autoincrement=True,
            postgresql_using="id::integer",
        )
        if "ix_groups_id" in existing_indexes:
            batch_op.drop_index(batch_op.f("ix_groups_id"))
    # ### commands auto generated by Alembic - please adjust! ###
    safe_create_table(
        "chats",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    safe_create_table(
        "news",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("content_en", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("news", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_created_at"), ["created_at"], unique=False
        )

    safe_create_table(
        "schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(), nullable=False),
        sa.Column("teacher", sa.String(), nullable=True),
        sa.Column("room", sa.String(), nullable=True),
        sa.Column("weekday", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parity", sa.String(), nullable=True),
        sa.Column("lesson_type", sa.String(), nullable=True),
        sa.CheckConstraint("end_time > start_time", name="ck_schedule_time_order"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schedule_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_group_id"), ["group_id"], unique=False
        )
        batch_op.create_index(
            "ix_schedule_group_start_time", ["group_id", "start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_parity"), ["parity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_start_time"), ["start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_schedule_weekday"), ["weekday"], unique=False
        )

    safe_create_table(
        "chat_participants",
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("chat_id", "user_id"),
    )
    safe_create_table(
        "data_access_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("subject_user_id", sa.Integer(), nullable=True),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("signature", sa.String(length=512), nullable=True),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["subject_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", "created_at")
        if is_postgresql
        else sa.PrimaryKeyConstraint("id"),
        postgresql_partition_by="RANGE (created_at)",
    )
    with safe_batch_alter_table("data_access_logs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_actor_user_id"),
            ["actor_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_resource_id"), ["resource_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_resource_type"),
            ["resource_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_data_access_logs_subject_user_id"),
            ["subject_user_id"],
            unique=False,
        )

    safe_create_table(
        "email_change_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("new_email", sa.String(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("email_change_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_new_email"), ["new_email"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_used"), ["used"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_email_change_tokens_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_en", sa.Text(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("location_en", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=True),
        sa.Column("event_type_en", sa.String(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "search_vector",
            sa.Text().with_variant(postgresql.TSVECTOR(), "postgresql"),
            server_default=sa.FetchedValue(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("speaker", sa.String(), nullable=True),
        sa.Column("image_url", sa.String(), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("about_en", sa.Text(), nullable=True),
        sa.CheckConstraint("ends_at > starts_at", name="ck_event_time_order"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_ends_at"), ["ends_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_events_starts_at"), ["starts_at"], unique=False
        )

    safe_create_table(
        "invite_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("used_by_user_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "role IN ('student', 'teacher', 'admin')", name="ck_invite_codes_role_valid"
        ),
        sa.ForeignKeyConstraint(["used_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_invite_codes_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_invite_codes_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invite_codes_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invite_codes_is_used"), ["is_used"], unique=False
        )

    safe_create_table(
        "messages",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_status", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sender_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    safe_create_table(
        "news_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["news_id"], ["news.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("news_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_comments_news_id"), ["news_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_news_comments_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "news_likes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("news_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["news_id"], ["news.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("news_likes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_news_likes_news_id"), ["news_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_news_likes_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("title_en", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("body_en", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("dedupe_key", sa.String(length=255), nullable=True),
        sa.Column("read", sa.Boolean(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "created_at")
        if is_postgresql
        else sa.PrimaryKeyConstraint("id"),
        postgresql_partition_by="RANGE (created_at)",
    )
    with safe_batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_dedupe_key"), ["dedupe_key"], unique=False
        )
        batch_op.create_index(
            "ix_notifications_dupe_check",
            ["user_id", "title", "url", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_read"), ["read"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_read_at"), ["read_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_type"), ["type"], unique=False
        )
        batch_op.create_index(
            "ix_notifications_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_notifications_user_dedupe", ["user_id", "dedupe_key"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "password_reset_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_created_at"),
            ["created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_expires_at"),
            ["expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_token_hash"),
            ["token_hash"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_used"), ["used"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_password_reset_tokens_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "spotify_integrations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("spotify_user_id", sa.String(), nullable=True),
        sa.Column(
            "access_token", app.utils.encryption.EncryptedString(), nullable=True
        ),
        sa.Column(
            "refresh_token", app.utils.encryption.EncryptedString(), nullable=True
        ),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("is_connected", sa.Boolean(), nullable=True),
        sa.Column("is_playing", sa.Boolean(), nullable=True),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_track_id", sa.String(), nullable=True),
        sa.Column("last_track_name", sa.String(), nullable=True),
        sa.Column("last_artist_name", sa.String(), nullable=True),
        sa.Column("last_album_name", sa.String(), nullable=True),
        sa.Column("last_track_url", sa.String(), nullable=True),
        sa.Column("last_album_image_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    with safe_batch_alter_table("spotify_integrations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_is_connected"),
            ["is_connected"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_is_playing"),
            ["is_playing"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_last_checked_at"),
            ["last_checked_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_last_track_id"),
            ["last_track_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_spotify_user_id"),
            ["spotify_user_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_spotify_integrations_token_expires_at"),
            ["token_expires_at"],
            unique=False,
        )

    safe_create_table(
        "trusted_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("trusted_devices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_trusted_devices_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_trusted_devices_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_trusted_devices_last_used_at"),
            ["last_used_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_trusted_devices_token_hash"), ["token_hash"], unique=True
        )

    safe_create_table(
        "user_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("dnd_enabled", sa.Boolean(), nullable=False),
        sa.Column("dnd_start", sa.Time(), nullable=True),
        sa.Column("dnd_end", sa.Time(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    safe_create_table(
        "webauthn_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("backing_up", sa.Boolean(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_webauthn_credentials_credential_id"),
            ["credential_id"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_webauthn_credentials_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "attachments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("file_type", sa.String(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    safe_create_table(
        "event_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "registered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("qr_secret", sa.String(), nullable=False),
        sa.Column("qr_hmac", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "event_id", name="uq_event_attendance_user_event"
        ),
    )
    with safe_batch_alter_table("event_attendance", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_attendance_event_id"), ["event_id"], unique=False
        )
        batch_op.create_index(
            "ix_event_attendance_event_user", ["event_id", "user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_attendance_registered_at"),
            ["registered_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_event_attendance_user_id"), ["user_id"], unique=False
        )

    safe_create_table(
        "event_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("file_url", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["event_id"], ["events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with safe_batch_alter_table("event_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_files_event_id"), ["event_id"], unique=False
        )

    safe_create_table(
        "notification_deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("notification_id", sa.Integer(), nullable=False),
        sa.Column(
            "notification_created_at", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "attempted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["notification_id", "notification_created_at"],
            ["notifications.id", "notifications.created_at"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", "attempted_at")
        if is_postgresql
        else sa.PrimaryKeyConstraint("id"),
        postgresql_partition_by="RANGE (attempted_at)",
    )
    with safe_batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_attempted_at"),
            ["attempted_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_channel"), ["channel"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_delivered_at"),
            ["delivered_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_notification_deliveries_notif_channel",
            ["notification_id", "channel"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_notification_id"),
            ["notification_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_notification_deliveries_status"), ["status"], unique=False
        )

    existing_constraints = {
        c["name"] for c in inspector.get_unique_constraints("active_sessions")
    }

    with safe_batch_alter_table("active_sessions", schema=None) as batch_op:
        batch_op.alter_column("signing_key", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_index(batch_op.f("ix_active_sessions_user_last_seen"))
        if "uq_active_sessions_jti" in existing_constraints:
            batch_op.drop_constraint(
                batch_op.f("uq_active_sessions_jti"), type_="unique"
            )

    if inspector.has_table("failed_login_attempts"):
        existing_failed_login_indexes = {
            i["name"] for i in inspector.get_indexes("failed_login_attempts")
        }

        with safe_batch_alter_table("failed_login_attempts", schema=None) as batch_op:
            if "ix_failed_login_attempts_user_id" not in existing_failed_login_indexes:
                batch_op.create_index(
                    batch_op.f("ix_failed_login_attempts_user_id"),
                    ["user_id"],
                    unique=False,
                )

    if inspector.has_table("mfa_challenges"):
        existing_mfa_indexes = {
            i["name"] for i in inspector.get_indexes("mfa_challenges")
        }
        with safe_batch_alter_table("mfa_challenges", schema=None) as batch_op:
            if "ix_mfa_challenges_session_id" in existing_mfa_indexes:
                batch_op.drop_index(batch_op.f("ix_mfa_challenges_session_id"))

    if inspector.has_table("notification_queue_jobs"):
        existing_jobs_indexes = {
            i["name"] for i in inspector.get_indexes("notification_queue_jobs")
        }
        with safe_batch_alter_table("notification_queue_jobs", schema=None) as batch_op:
            if "ix_notification_queue_jobs_kind" not in existing_jobs_indexes:
                batch_op.create_index(
                    batch_op.f("ix_notification_queue_jobs_kind"),
                    ["kind"],
                    unique=False,
                )

    if inspector.has_table("user_push_topics"):
        existing_push_topics_indexes = {
            i["name"] for i in inspector.get_indexes("user_push_topics")
        }
        with safe_batch_alter_table("user_push_topics", schema=None) as batch_op:
            if "ix_user_push_topics_updated_at" in existing_push_topics_indexes:
                batch_op.drop_index(batch_op.f("ix_user_push_topics_updated_at"))
            if "ix_user_push_topics_user_id" not in existing_push_topics_indexes:
                batch_op.create_index(
                    batch_op.f("ix_user_push_topics_user_id"), ["user_id"], unique=False
                )

    if inspector.has_table("users"):
        existing_users_indexes = {i["name"] for i in inspector.get_indexes("users")}
        existing_users_columns = {c["name"] for c in inspector.get_columns("users")}
        existing_users_fks = {fk["name"] for fk in inspector.get_foreign_keys("users")}

        with safe_batch_alter_table("users", schema=None) as batch_op:
            if "group_id" not in existing_users_columns:
                batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
            if "webauthn_id" not in existing_users_columns:
                batch_op.add_column(
                    sa.Column("webauthn_id", sa.String(length=128), nullable=True)
                )
            if "avatar_url" not in existing_users_columns:
                batch_op.add_column(sa.Column("avatar_url", sa.String(), nullable=True))
            if "cover_url" not in existing_users_columns:
                batch_op.add_column(sa.Column("cover_url", sa.String(), nullable=True))
            if "about" not in existing_users_columns:
                batch_op.add_column(sa.Column("about", sa.String(), nullable=True))
            if "record_book_number" not in existing_users_columns:
                batch_op.add_column(
                    sa.Column("record_book_number", sa.String(), nullable=True)
                )
            if "status" not in existing_users_columns:
                batch_op.add_column(sa.Column("status", sa.String(), nullable=True))
            if "institute" not in existing_users_columns:
                batch_op.add_column(sa.Column("institute", sa.String(), nullable=True))
            if "course" not in existing_users_columns:
                batch_op.add_column(sa.Column("course", sa.String(), nullable=True))
            if "education_level" not in existing_users_columns:
                batch_op.add_column(
                    sa.Column("education_level", sa.String(), nullable=True)
                )
            if "track" not in existing_users_columns:
                batch_op.add_column(sa.Column("track", sa.String(), nullable=True))
            if "program" not in existing_users_columns:
                batch_op.add_column(sa.Column("program", sa.String(), nullable=True))
            if "telegram" not in existing_users_columns:
                batch_op.add_column(sa.Column("telegram", sa.String(), nullable=True))
            if "achievements" not in existing_users_columns:
                batch_op.add_column(
                    sa.Column("achievements", sa.String(), nullable=True)
                )

            if "ix_users_id" in existing_users_indexes:
                batch_op.drop_index(batch_op.f("ix_users_id"))
            if "ix_users_spotify_last_track_id" in existing_users_indexes:
                batch_op.drop_index(batch_op.f("ix_users_spotify_last_track_id"))
            if "ix_users_spotify_token_expires_at" in existing_users_indexes:
                batch_op.drop_index(batch_op.f("ix_users_spotify_token_expires_at"))
            if "ix_users_spotify_user_id" in existing_users_indexes:
                batch_op.drop_index(batch_op.f("ix_users_spotify_user_id"))

            if "ix_users_group_id" not in existing_users_indexes:
                batch_op.create_index(
                    batch_op.f("ix_users_group_id"), ["group_id"], unique=False
                )
            if "ix_users_webauthn_id" not in existing_users_indexes:
                batch_op.create_index(
                    batch_op.f("ix_users_webauthn_id"), ["webauthn_id"], unique=True
                )

            if "fk_users_group_id_groups" not in existing_users_fks:
                batch_op.create_foreign_key(
                    "fk_users_group_id_groups",
                    "groups",
                    ["group_id"],
                    ["id"],
                    ondelete="SET NULL",
                )

            if "spotify_access_token" in existing_users_columns:
                batch_op.drop_column("spotify_access_token")
            if "spotify_last_track_url" in existing_users_columns:
                batch_op.drop_column("spotify_last_track_url")
            if "spotify_refresh_token" in existing_users_columns:
                batch_op.drop_column("spotify_refresh_token")
            if "spotify_last_album_image_url" in existing_users_columns:
                batch_op.drop_column("spotify_last_album_image_url")
            if "dnd_end" in existing_users_columns:
                batch_op.drop_column("dnd_end")
            if "spotify_scope" in existing_users_columns:
                batch_op.drop_column("spotify_scope")
            if "spotify_last_track_id" in existing_users_columns:
                batch_op.drop_column("spotify_last_track_id")
            if "spotify_last_checked_at" in existing_users_columns:
                batch_op.drop_column("spotify_last_checked_at")
            if "dnd_start" in existing_users_columns:
                batch_op.drop_column("dnd_start")
            if "dnd_enabled" in existing_users_columns:
                batch_op.drop_column("dnd_enabled")
            if "spotify_token_expires_at" in existing_users_columns:
                batch_op.drop_column("spotify_token_expires_at")
            if "timezone" in existing_users_columns:
                batch_op.drop_column("timezone")
            if "spotify_user_id" in existing_users_columns:
                batch_op.drop_column("spotify_user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with safe_batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("spotify_user_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("timezone", sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(
            sa.Column("spotify_token_expires_at", sa.DATETIME(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "dnd_enabled",
                sa.BOOLEAN(),
                server_default=sa.text("(false)"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("dnd_start", sa.TIME(), nullable=True))
        batch_op.add_column(
            sa.Column("spotify_last_checked_at", sa.DATETIME(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("spotify_last_track_id", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(sa.Column("spotify_scope", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("dnd_end", sa.TIME(), nullable=True))
        batch_op.add_column(
            sa.Column("spotify_last_album_image_url", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("spotify_refresh_token", sa.TEXT(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("spotify_last_track_url", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(sa.Column("spotify_access_token", sa.TEXT(), nullable=True))
        batch_op.drop_constraint("fk_users_group_id_groups", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_users_webauthn_id"))
        batch_op.drop_index(batch_op.f("ix_users_group_id"))
        batch_op.create_index(
            batch_op.f("ix_users_spotify_user_id"), ["spotify_user_id"], unique=1
        )
        batch_op.create_index(
            batch_op.f("ix_users_spotify_token_expires_at"),
            ["spotify_token_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_users_spotify_last_track_id"),
            ["spotify_last_track_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.drop_column("achievements")
        batch_op.drop_column("telegram")
        batch_op.drop_column("program")
        batch_op.drop_column("track")
        batch_op.drop_column("education_level")
        batch_op.drop_column("course")
        batch_op.drop_column("institute")
        batch_op.drop_column("status")
        batch_op.drop_column("record_book_number")
        batch_op.drop_column("about")
        batch_op.drop_column("cover_url")
        batch_op.drop_column("avatar_url")
        batch_op.drop_column("webauthn_id")
        batch_op.drop_column("group_id")

    with safe_batch_alter_table("user_push_topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_push_topics_user_id"))
        batch_op.create_index(
            batch_op.f("ix_user_push_topics_updated_at"), ["updated_at"], unique=False
        )

    with safe_batch_alter_table("notification_queue_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_queue_jobs_kind"))

    with safe_batch_alter_table("mfa_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_mfa_challenges_session_id"), ["session_id"], unique=False
        )

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_indexes = {i["name"] for i in inspector.get_indexes("groups")}

    existing_columns = {c["name"] for c in inspector.get_columns("groups")}

    with safe_batch_alter_table("groups", schema=None) as batch_op:
        if "ix_groups_id" not in existing_indexes:
            batch_op.create_index(batch_op.f("ix_groups_id"), ["id"], unique=False)
        batch_op.alter_column(
            "id",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
            autoincrement=True,
        )
        if "faculty" in existing_columns:
            batch_op.drop_column("faculty")
        if "course" in existing_columns:
            batch_op.drop_column("course")

    if inspector.has_table("failed_login_attempts"):
        existing_failed_login_indexes = {
            i["name"] for i in inspector.get_indexes("failed_login_attempts")
        }

        with safe_batch_alter_table("failed_login_attempts", schema=None) as batch_op:
            if "ix_failed_login_attempts_user_id" in existing_failed_login_indexes:
                batch_op.drop_index(batch_op.f("ix_failed_login_attempts_user_id"))

    existing_active_sessions_constraints = {
        c["name"] for c in inspector.get_unique_constraints("active_sessions")
    }

    with safe_batch_alter_table("active_sessions", schema=None) as batch_op:
        if "uq_active_sessions_jti" not in existing_active_sessions_constraints:
            batch_op.create_unique_constraint(
                batch_op.f("uq_active_sessions_jti"), ["jti"]
            )
        batch_op.create_index(
            batch_op.f("ix_active_sessions_user_last_seen"),
            ["user_id", "last_seen_at"],
            unique=False,
        )
        batch_op.alter_column("signing_key", existing_type=sa.VARCHAR(), nullable=True)

    with safe_batch_alter_table("notification_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_status"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_notification_id"))
        batch_op.drop_index("ix_notification_deliveries_notif_channel")
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_delivered_at"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_channel"))
        batch_op.drop_index(batch_op.f("ix_notification_deliveries_attempted_at"))

    op.drop_table("notification_deliveries")
    with op.batch_alter_table("event_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_files_event_id"))

    op.drop_table("event_files")
    with op.batch_alter_table("event_attendance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_attendance_user_id"))
        batch_op.drop_index(batch_op.f("ix_event_attendance_registered_at"))
        batch_op.drop_index("ix_event_attendance_event_user")
        batch_op.drop_index(batch_op.f("ix_event_attendance_event_id"))

    op.drop_table("event_attendance")
    op.drop_table("attachments")
    with op.batch_alter_table("webauthn_credentials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_webauthn_credentials_user_id"))
        batch_op.drop_index(batch_op.f("ix_webauthn_credentials_credential_id"))

    op.drop_table("webauthn_credentials")
    op.drop_table("user_preferences")
    with op.batch_alter_table("trusted_devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_trusted_devices_token_hash"))
        batch_op.drop_index(batch_op.f("ix_trusted_devices_last_used_at"))
        batch_op.drop_index(batch_op.f("ix_trusted_devices_id"))
        batch_op.drop_index(batch_op.f("ix_trusted_devices_expires_at"))

    op.drop_table("trusted_devices")
    with op.batch_alter_table("spotify_integrations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_token_expires_at"))
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_spotify_user_id"))
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_last_track_id"))
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_last_checked_at"))
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_is_playing"))
        batch_op.drop_index(batch_op.f("ix_spotify_integrations_is_connected"))

    op.drop_table("spotify_integrations")
    with op.batch_alter_table("password_reset_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_used"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_expires_at"))
        batch_op.drop_index(batch_op.f("ix_password_reset_tokens_created_at"))

    op.drop_table("password_reset_tokens")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index("ix_notifications_user_dedupe")
        batch_op.drop_index("ix_notifications_user_created")
        batch_op.drop_index(batch_op.f("ix_notifications_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_read_at"))
        batch_op.drop_index(batch_op.f("ix_notifications_read"))
        batch_op.drop_index("ix_notifications_dupe_check")
        batch_op.drop_index(batch_op.f("ix_notifications_dedupe_key"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("news_likes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_likes_user_id"))
        batch_op.drop_index(batch_op.f("ix_news_likes_news_id"))

    op.drop_table("news_likes")
    with op.batch_alter_table("news_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_comments_user_id"))
        batch_op.drop_index(batch_op.f("ix_news_comments_news_id"))

    op.drop_table("news_comments")
    op.drop_table("messages")
    with op.batch_alter_table("invite_codes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invite_codes_is_used"))
        batch_op.drop_index(batch_op.f("ix_invite_codes_is_active"))
        batch_op.drop_index(batch_op.f("ix_invite_codes_created_at"))
        batch_op.drop_index(batch_op.f("ix_invite_codes_code"))

    op.drop_table("invite_codes")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_starts_at"))
        batch_op.drop_index(batch_op.f("ix_events_is_active"))
        batch_op.drop_index(batch_op.f("ix_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_events_ends_at"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))

    op.drop_table("events")
    with op.batch_alter_table("email_change_tokens", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_user_id"))
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_used"))
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_token_hash"))
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_new_email"))
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_expires_at"))
        batch_op.drop_index(batch_op.f("ix_email_change_tokens_created_at"))

    op.drop_table("email_change_tokens")
    with op.batch_alter_table("data_access_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_data_access_logs_subject_user_id"))
        batch_op.drop_index(batch_op.f("ix_data_access_logs_resource_type"))
        batch_op.drop_index(batch_op.f("ix_data_access_logs_resource_id"))
        batch_op.drop_index(batch_op.f("ix_data_access_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_data_access_logs_actor_user_id"))
        batch_op.drop_index(batch_op.f("ix_data_access_logs_action"))

    op.drop_table("data_access_logs")
    op.drop_table("chat_participants")
    with op.batch_alter_table("schedule", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedule_weekday"))
        batch_op.drop_index(batch_op.f("ix_schedule_start_time"))
        batch_op.drop_index(batch_op.f("ix_schedule_parity"))
        batch_op.drop_index("ix_schedule_group_start_time")
        batch_op.drop_index(batch_op.f("ix_schedule_group_id"))
        batch_op.drop_index(batch_op.f("ix_schedule_end_time"))

    op.drop_table("schedule")
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_news_created_at"))

    op.drop_table("news")
    op.drop_table("chats")
    # ### end Alembic commands ###
