"""add_pgvector_embeddings

Revision ID: 1b15294cc8d7
Revises: 3f1cf9168805
Create Date: 2026-01-25 01:24:37.181174

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b15294cc8d7"
down_revision: str | None = "3f1cf9168805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True)
        )

    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True)
        )

    # Add HNSW indexes for cosine distance
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            "CREATE INDEX ix_news_embedding_hnsw ON news "
            "USING hnsw (embedding vector_cosine_ops)"
        )
        op.execute(
            "CREATE INDEX ix_events_embedding_hnsw ON events "
            "USING hnsw (embedding vector_cosine_ops)"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("news", schema=None) as batch_op:
        batch_op.drop_column("embedding")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("embedding")
        batch_op.drop_column("search_vector")

    # ### end Alembic commands ###
