"""add_pgvector_embeddings

Revision ID: 1b15294cc8d7
Revises: 3f1cf9168805
Create Date: 2026-01-25 01:24:37.181174

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b15294cc8d7"
down_revision: str | None = "3f1cf9168805"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # Enable pgvector extension
    if bind.dialect.name == "postgresql":
        op.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))

    # ### commands auto generated by Alembic - please adjust! ###
    if "events" in existing_tables:
        with op.batch_alter_table("events", schema=None) as batch_op:
            existing_columns = {c["name"] for c in inspector.get_columns("events")}
            if "embedding" not in existing_columns:
                batch_op.add_column(
                    sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True)
                )

    if "news" in existing_tables:
        with op.batch_alter_table("news", schema=None) as batch_op:
            existing_columns = {c["name"] for c in inspector.get_columns("news")}
            if "embedding" not in existing_columns:
                batch_op.add_column(
                    sa.Column("embedding", pgvector.sqlalchemy.Vector(dim=1536), nullable=True)
                )

    # Add HNSW indexes for cosine distance
    if bind.dialect.name == "postgresql":
        if "news" in existing_tables:
            existing_indexes = {i["name"] for i in inspector.get_indexes("news")}
            if "ix_news_embedding_hnsw" not in existing_indexes:
                op.execute(
                    "CREATE INDEX ix_news_embedding_hnsw ON news "
                    "USING hnsw (embedding vector_cosine_ops)"
                )
        if "events" in existing_tables:
            existing_indexes = {i["name"] for i in inspector.get_indexes("events")}
            if "ix_events_embedding_hnsw" not in existing_indexes:
                op.execute(
                    "CREATE INDEX ix_events_embedding_hnsw ON events "
                    "USING hnsw (embedding vector_cosine_ops)"
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "news" in existing_tables:
        with op.batch_alter_table("news", schema=None) as batch_op:
            existing_columns = {c["name"] for c in inspector.get_columns("news")}
            if "embedding" in existing_columns:
                batch_op.drop_column("embedding")

    if "events" in existing_tables:
        with op.batch_alter_table("events", schema=None) as batch_op:
            existing_columns = {c["name"] for c in inspector.get_columns("events")}
            if "embedding" in existing_columns:
                batch_op.drop_column("embedding")

    # ### end Alembic commands ###
