"""Add recovery codes

Revision ID: 202601130002
Revises: 202601130001
Create Date: 2026-01-13 17:00:00.000000

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "202601130002"
down_revision = "202601130001"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if not inspector.has_table("recovery_codes"):
        op.create_table(
            "recovery_codes",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("code_hash", sa.String(length=255), nullable=False),
            sa.Column("is_used", sa.Boolean(), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )

    # Check for indexes
    indexes = (
        {ix["name"] for ix in inspector.get_indexes("recovery_codes")}
        if inspector.has_table("recovery_codes")
        else set()
    )

    if "ix_recovery_codes_is_used" not in indexes:
        op.create_index(
            op.f("ix_recovery_codes_is_used"),
            "recovery_codes",
            ["is_used"],
            unique=False,
        )
    if "ix_recovery_codes_user_id" not in indexes:
        op.create_index(
            op.f("ix_recovery_codes_user_id"),
            "recovery_codes",
            ["user_id"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if inspector.has_table("recovery_codes"):
        # Indexes are dropped automatically with the table, but explicit drop is okay
        # if guarded or we just drop the table.
        # Alembic usually generates drop_index before drop_table.
        op.drop_table("recovery_codes")
    # ### end Alembic commands ###
