"""add_signature_to_data_access_logs

Revision ID: 31e81f57c53d
Revises: ab93b27831f3
Create Date: 2025-12-21 21:46:39.483334

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "31e81f57c53d"
down_revision: str | None = "ab93b27831f3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite - data_access_logs uses PostgreSQL-specific types
    if bind.dialect.name == "sqlite":
        return

    # Skip if data_access_logs table doesn't exist (fresh database)
    inspector = sa.inspect(bind)
    if "data_access_logs" not in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_access_logs", sa.Column("signature", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite
    if bind.dialect.name == "sqlite":
        return

    # Skip if data_access_logs table doesn't exist (fresh database)
    inspector = sa.inspect(bind)
    if "data_access_logs" not in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    # Check if column exists before dropping
    existing_columns = {
        col["name"] for col in inspector.get_columns("data_access_logs")
    }
    if "signature" in existing_columns:
        op.drop_column("data_access_logs", "signature")
    # ### end Alembic commands ###
