"""decompose_user_model

Revision ID: 3f1cf9168805
Revises: 57bdf5bf9375
Create Date: 2026-01-25 01:08:36.016412

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1cf9168805"
down_revision: str | None = "57bdf5bf9375"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_education_paths",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("institute", sa.String(), nullable=True),
        sa.Column("course", sa.String(), nullable=True),
        sa.Column("education_level", sa.String(), nullable=True),
        sa.Column("track", sa.String(), nullable=True),
        sa.Column("program", sa.String(), nullable=True),
        sa.Column("record_book_number", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_profile_details",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("about", sa.String(), nullable=True),
        sa.Column("telegram", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("achievements", sa.String(), nullable=True),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("department", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )

    # Data Migration: Move data from users to new tables
    op.execute(
        """
        INSERT INTO user_education_paths (
            user_id, institute, course, education_level, track, program,
            record_book_number
        )
        SELECT
            id, institute, course, education_level, track, program,
            record_book_number
        FROM users
        """
    )
    op.execute(
        """
        INSERT INTO user_profile_details (
            user_id, about, telegram, status, achievements, position, department
        )
        SELECT
            id, about, telegram, status, achievements, position, department
        FROM users
        """
    )

    with op.batch_alter_table("dead_letter_jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dead_letter_jobs_job_type"))
        batch_op.drop_index(batch_op.f("ix_dead_letter_jobs_next_retry_at"))
        batch_op.drop_index(batch_op.f("ix_dead_letter_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_dlq_status_next_retry"))

    op.drop_table("dead_letter_jobs")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("program")
        batch_op.drop_column("department")
        batch_op.drop_column("record_book_number")
        batch_op.drop_column("status")
        batch_op.drop_column("education_level")
        batch_op.drop_column("institute")
        batch_op.drop_column("telegram")
        batch_op.drop_column("achievements")
        batch_op.drop_column("position")
        batch_op.drop_column("about")
        batch_op.drop_column("track")
        batch_op.drop_column("course")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("course", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("track", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("about", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("position", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("achievements", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("telegram", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("institute", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("education_level", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("status", sa.VARCHAR(), nullable=True))
        batch_op.add_column(
            sa.Column("record_book_number", sa.VARCHAR(), nullable=True)
        )
        batch_op.add_column(sa.Column("department", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("program", sa.VARCHAR(), nullable=True))

    # Data Restoration: Move data back from new tables to users
    if is_postgres:
        op.execute(
            """
            UPDATE users
            SET
                institute = ep.institute,
                course = ep.course,
                education_level = ep.education_level,
                track = ep.track,
                program = ep.program,
                record_book_number = ep.record_book_number
            FROM user_education_paths ep
            WHERE users.id = ep.user_id
            """
        )
        op.execute(
            """
            UPDATE users
            SET
                about = pd.about,
                telegram = pd.telegram,
                status = pd.status,
                achievements = pd.achievements,
                position = pd.position,
                department = pd.department
            FROM user_profile_details pd
            WHERE users.id = pd.user_id
            """
        )
    else:
        # SQLite compatible updates
        for table, fields in [
            (
                "user_education_paths",
                [
                    "institute",
                    "course",
                    "education_level",
                    "track",
                    "program",
                    "record_book_number",
                ],
            ),
            (
                "user_profile_details",
                [
                    "about",
                    "telegram",
                    "status",
                    "achievements",
                    "position",
                    "department",
                ],
            ),
        ]:
            set_clause = ", ".join(
                [
                    f"{f} = (SELECT {f} FROM {table} WHERE {table}.user_id = users.id)"
                    for f in fields
                ]
            )
            op.execute(
                f"UPDATE users SET {set_clause} "
                f"WHERE id IN (SELECT user_id FROM {table})"
            )

    op.create_table(
        "dead_letter_jobs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("job_type", sa.VARCHAR(length=100), nullable=False),
        sa.Column("job_hash", sa.VARCHAR(length=64), nullable=False),
        sa.Column("payload", sa.TEXT(), nullable=False),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column(
            "retry_count", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column(
            "max_retries", sa.INTEGER(), server_default=sa.text("'3'"), nullable=False
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending'"),
            nullable=False,
        ),
        sa.Column("next_retry_at", sa.DATETIME(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("job_hash"),
    )
    with op.batch_alter_table("dead_letter_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dlq_status_next_retry"),
            ["status", "next_retry_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_dead_letter_jobs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_dead_letter_jobs_next_retry_at"),
            ["next_retry_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_dead_letter_jobs_job_type"), ["job_type"], unique=False
        )

    op.drop_table("user_profile_details")
    op.drop_table("user_education_paths")
    # ### end Alembic commands ###
