"""decompose_user_model

Revision ID: 3f1cf9168805
Revises: 57bdf5bf9375
Create Date: 2026-01-25 01:08:36.016412

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1cf9168805"
down_revision: str | None = "57bdf5bf9375"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if "user_education_paths" not in existing_tables:
        op.create_table(
            "user_education_paths",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("institute", sa.String(), nullable=True),
            sa.Column("course", sa.String(), nullable=True),
            sa.Column("education_level", sa.String(), nullable=True),
            sa.Column("track", sa.String(), nullable=True),
            sa.Column("program", sa.String(), nullable=True),
            sa.Column("record_book_number", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("user_id"),
        )
    if "user_profile_details" not in existing_tables:
        op.create_table(
            "user_profile_details",
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("about", sa.String(), nullable=True),
            sa.Column("telegram", sa.String(), nullable=True),
            sa.Column("status", sa.String(), nullable=True),
            sa.Column("achievements", sa.String(), nullable=True),
            sa.Column("position", sa.String(), nullable=True),
            sa.Column("department", sa.String(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("user_id"),
        )

    existing_users_columns = {c["name"] for c in inspector.get_columns("users")}

    # Data Migration: Move data from users to new tables
    if "institute" in existing_users_columns:
        op.execute(
            """
            INSERT INTO user_education_paths (
                user_id, institute, course, education_level, track, program,
                record_book_number
            )
            SELECT
                id, institute, course, education_level, track, program,
                record_book_number
            FROM users
            WHERE true
            ON CONFLICT (user_id) DO NOTHING
            """
        )
    if "about" in existing_users_columns:
        op.execute(
            """
            INSERT INTO user_profile_details (
                user_id, about, telegram, status, achievements, position, department
            )
            SELECT
                id, about, telegram, status, achievements, position, department
            FROM users
            WHERE true
            ON CONFLICT (user_id) DO NOTHING
            """
        )

    # Removed erroneous table drop - model was missing from registration
    # but table is still needed

    with op.batch_alter_table("users", schema=None) as batch_op:
        for col in [
            "program",
            "department",
            "record_book_number",
            "status",
            "education_level",
            "institute",
            "telegram",
            "achievements",
            "position",
            "about",
            "track",
            "course",
        ]:
            if col in existing_users_columns:
                batch_op.drop_column(col)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_postgres = bind.dialect.name == "postgresql"

    # ### commands auto generated by Alembic - please adjust! ###
    inspector = sa.inspect(bind)
    existing_users_columns = {c["name"] for c in inspector.get_columns("users")}
    with op.batch_alter_table("users", schema=None) as batch_op:
        if "course" not in existing_users_columns:
            batch_op.add_column(sa.Column("course", sa.VARCHAR(), nullable=True))
        if "track" not in existing_users_columns:
            batch_op.add_column(sa.Column("track", sa.VARCHAR(), nullable=True))
        if "about" not in existing_users_columns:
            batch_op.add_column(sa.Column("about", sa.VARCHAR(), nullable=True))
        if "position" not in existing_users_columns:
            batch_op.add_column(sa.Column("position", sa.VARCHAR(), nullable=True))
        if "achievements" not in existing_users_columns:
            batch_op.add_column(sa.Column("achievements", sa.VARCHAR(), nullable=True))
        if "telegram" not in existing_users_columns:
            batch_op.add_column(sa.Column("telegram", sa.VARCHAR(), nullable=True))
        if "institute" not in existing_users_columns:
            batch_op.add_column(sa.Column("institute", sa.VARCHAR(), nullable=True))
        if "education_level" not in existing_users_columns:
            batch_op.add_column(
                sa.Column("education_level", sa.VARCHAR(), nullable=True)
            )
        if "status" not in existing_users_columns:
            batch_op.add_column(sa.Column("status", sa.VARCHAR(), nullable=True))
        if "record_book_number" not in existing_users_columns:
            batch_op.add_column(
                sa.Column("record_book_number", sa.VARCHAR(), nullable=True)
            )
        if "department" not in existing_users_columns:
            batch_op.add_column(sa.Column("department", sa.VARCHAR(), nullable=True))
        if "program" not in existing_users_columns:
            batch_op.add_column(sa.Column("program", sa.VARCHAR(), nullable=True))

    # Data Restoration: Move data back from new tables to users
    if is_postgres:
        if inspector.has_table("user_education_paths"):
            op.execute(
                """
                UPDATE users
                SET
                    institute = ep.institute,
                    course = ep.course,
                    education_level = ep.education_level,
                    track = ep.track,
                    program = ep.program,
                    record_book_number = ep.record_book_number
                FROM user_education_paths ep
                WHERE users.id = ep.user_id
                """
            )
        if inspector.has_table("user_profile_details"):
            op.execute(
                """
                UPDATE users
                SET
                    about = pd.about,
                    telegram = pd.telegram,
                    status = pd.status,
                    achievements = pd.achievements,
                    position = pd.position,
                    department = pd.department
                FROM user_profile_details pd
                WHERE users.id = pd.user_id
                """
            )
    else:
        # SQLite compatible updates
        for table, fields in [
            (
                "user_education_paths",
                [
                    "institute",
                    "course",
                    "education_level",
                    "track",
                    "program",
                    "record_book_number",
                ],
            ),
            (
                "user_profile_details",
                [
                    "about",
                    "telegram",
                    "status",
                    "achievements",
                    "position",
                    "department",
                ],
            ),
        ]:
            if inspector.has_table(table):
                set_clause = ", ".join(
                    [
                        f"{f} = (SELECT {f} FROM {table} WHERE {table}.user_id = users.id)"  # noqa: S608
                        for f in fields
                    ]
                )
                op.execute(
                    f"UPDATE users SET {set_clause} "  # noqa: S608
                    f"WHERE id IN (SELECT user_id FROM {table})"
                )

    if inspector.has_table("user_profile_details"):
        op.drop_table("user_profile_details")
    if inspector.has_table("user_education_paths"):
        op.drop_table("user_education_paths")
    # ### end Alembic commands ###
