"""Add missing outbox columns to stored_events

Revision ID: 40c81cc4a086
Revises: 0d36ef3a49c2
Create Date: 2026-03-14 02:39:07.585696

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40c81cc4a086"  # pragma: allowlist secret
down_revision: str | None = "0d36ef3a49c2"  # pragma: allowlist secret
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if "stored_events" in tables:
        columns = [c["name"] for c in inspector.get_columns("stored_events")]

        if "subject" not in columns:
            op.add_column(
                "stored_events",
                sa.Column("subject", sa.String(length=255), nullable=True),
            )
            op.create_index(
                op.f("ix_stored_events_subject"),
                "stored_events",
                ["subject"],
                unique=False,
            )

        if "status" not in columns:
            op.add_column(
                "stored_events",
                sa.Column(
                    "status",
                    sa.String(length=20),
                    server_default="pending",
                    nullable=False,
                ),
            )
            op.create_index(
                op.f("ix_stored_events_status"),
                "stored_events",
                ["status"],
                unique=False,
            )

        if "trace_context" not in columns:
            op.add_column(
                "stored_events", sa.Column("trace_context", sa.JSON(), nullable=True)
            )

        # Add index for pending events if not exists
        existing_indexes = {i["name"] for i in inspector.get_indexes("stored_events")}
        if "ix_stored_events_pending" not in existing_indexes:
            op.create_index(
                "ix_stored_events_pending",
                "stored_events",
                ["status", "created_at"],
                unique=False,
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_stored_events_pending", table_name="stored_events", if_exists=True
    )
    op.drop_index(
        op.f("ix_stored_events_status"), table_name="stored_events", if_exists=True
    )
    op.drop_column("stored_events", "status")
    op.drop_index(
        op.f("ix_stored_events_subject"), table_name="stored_events", if_exists=True
    )
    op.drop_column("stored_events", "subject")
    op.drop_column("stored_events", "trace_context")
    # ### end Alembic commands ###
