"""add invite code table

Revision ID: 776d6f9def10
Revises: b05ae64aaeef
Create Date: 2025-05-31 16:22:23.073368

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "776d6f9def10"
down_revision: str | None = "b05ae64aaeef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
