"""add_webauthn_support_v2

Revision ID: ab93b27831f3
Revises: 202512210001
Create Date: 2025-12-21 11:04:32.338729

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab93b27831f3"
down_revision: str | None = "202512210001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite - this migration uses PostgreSQL-specific types and DROP COLUMN
    if bind.dialect.name == "sqlite":
        return

    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())

    # Helper to get existing indexes for a table
    def get_existing_indexes(table_name: str) -> set:
        if table_name not in existing_tables:
            return set()
        return {idx["name"] for idx in inspector.get_indexes(table_name)}

    # Helper to get existing columns for a table
    def get_existing_columns(table_name: str) -> set:
        if table_name not in existing_tables:
            return set()
        return {col["name"] for col in inspector.get_columns(table_name)}

    # ### commands auto generated by Alembic - please adjust! ###

    if "webauthn_credentials" not in existing_tables:
        op.create_table(
            "webauthn_credentials",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("credential_id", sa.String(), nullable=False),
            sa.Column("public_key", sa.Text(), nullable=False),
            sa.Column("sign_count", sa.Integer(), nullable=False),
            sa.Column("transports", sa.JSON(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            ),
            sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
            sa.Column("label", sa.String(length=255), nullable=True),
            sa.Column("backing_up", sa.Boolean(), nullable=True),
            sa.Column("backup_state", sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_webauthn_credentials_credential_id"),
            "webauthn_credentials",
            ["credential_id"],
            unique=True,
        )
        op.create_index(
            op.f("ix_webauthn_credentials_user_id"),
            "webauthn_credentials",
            ["user_id"],
            unique=False,
        )

    # Data access logs operations - only if table exists
    if "data_access_logs" in existing_tables:
        dal_indexes = get_existing_indexes("data_access_logs")
        op.alter_column(
            "data_access_logs",
            "context",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.JSON(),
            existing_nullable=True,
        )
        if "ix_data_access_logs_actor" in dal_indexes:
            op.drop_index(
                op.f("ix_data_access_logs_actor"), table_name="data_access_logs"
            )
        if "ix_data_access_logs_resource" in dal_indexes:
            op.drop_index(
                op.f("ix_data_access_logs_resource"), table_name="data_access_logs"
            )
        if "ix_data_access_logs_subject" in dal_indexes:
            op.drop_index(
                op.f("ix_data_access_logs_subject"), table_name="data_access_logs"
            )
        if "ix_data_access_logs_action" not in dal_indexes:
            op.create_index(
                op.f("ix_data_access_logs_action"),
                "data_access_logs",
                ["action"],
                unique=False,
            )
        if "ix_data_access_logs_actor_user_id" not in dal_indexes:
            op.create_index(
                op.f("ix_data_access_logs_actor_user_id"),
                "data_access_logs",
                ["actor_user_id"],
                unique=False,
            )
        if "ix_data_access_logs_resource_id" not in dal_indexes:
            op.create_index(
                op.f("ix_data_access_logs_resource_id"),
                "data_access_logs",
                ["resource_id"],
                unique=False,
            )
        if "ix_data_access_logs_resource_type" not in dal_indexes:
            op.create_index(
                op.f("ix_data_access_logs_resource_type"),
                "data_access_logs",
                ["resource_type"],
                unique=False,
            )
        if "ix_data_access_logs_subject_user_id" not in dal_indexes:
            op.create_index(
                op.f("ix_data_access_logs_subject_user_id"),
                "data_access_logs",
                ["subject_user_id"],
                unique=False,
            )

    # Users table operations
    if "users" in existing_tables:
        users_indexes = get_existing_indexes("users")
        users_columns = get_existing_columns("users")

        if "webauthn_id" not in users_columns:
            op.add_column(
                "users", sa.Column("webauthn_id", sa.String(length=128), nullable=True)
            )

        # Drop legacy spotify indexes if they exist
        for idx_name in [
            "ix_users_spotify_is_connected",
            "ix_users_spotify_is_playing",
            "ix_users_spotify_last_checked_at",
            "ix_users_spotify_last_track_id",
            "ix_users_spotify_token_expires_at",
            "ix_users_spotify_user_id",
        ]:
            if idx_name in users_indexes:
                op.drop_index(op.f(idx_name), table_name="users")

        if "ix_users_webauthn_id" not in users_indexes:
            op.create_index(
                op.f("ix_users_webauthn_id"), "users", ["webauthn_id"], unique=True
            )

        # Drop legacy spotify columns if they exist
        spotify_columns = [
            "spotify_token_expires_at",
            "spotify_last_album_name",
            "spotify_access_token",
            "spotify_is_connected",
            "spotify_refresh_token",
            "spotify_last_track_id",
            "spotify_last_track_name",
            "spotify_user_id",
            "spotify_last_track_url",
            "spotify_is_playing",
            "spotify_last_checked_at",
            "spotify_last_album_image_url",
            "spotify_last_artist_name",
            "spotify_scope",
            "spotify_display_name",
        ]
        for col_name in spotify_columns:
            if col_name in users_columns:
                op.drop_column("users", col_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite
    if bind.dialect.name == "sqlite":
        return

    # Skip on fresh databases - webauthn_credentials is created by this migration
    inspector = sa.inspect(bind)
    if "webauthn_credentials" not in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###

    # Pre-fetch indexes
    users_indexes = {ix["name"] for ix in inspector.get_indexes("users")}
    dal_indexes = (
        {ix["name"] for ix in inspector.get_indexes("data_access_logs")}
        if "data_access_logs" in inspector.get_table_names()
        else set()
    )

    columns = {col["name"] for col in inspector.get_columns("users")}
    if "spotify_display_name" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_display_name", sa.VARCHAR(), autoincrement=False, nullable=True
            ),
        )
    if "spotify_scope" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_scope", sa.VARCHAR(), autoincrement=False, nullable=True
            ),
        )
    if "spotify_last_artist_name" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_artist_name",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_last_album_image_url" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_album_image_url",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_last_checked_at" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_checked_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_is_playing" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_is_playing",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_last_track_url" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_track_url",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_user_id" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_user_id", sa.VARCHAR(), autoincrement=False, nullable=True
            ),
        )
    if "spotify_last_track_name" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_track_name",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_last_track_id" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_track_id",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_refresh_token" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_refresh_token", sa.TEXT(), autoincrement=False, nullable=True
            ),
        )
    if "spotify_is_connected" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_is_connected",
                sa.BOOLEAN(),
                server_default=sa.text("false"),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_access_token" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_access_token", sa.TEXT(), autoincrement=False, nullable=True
            ),
        )
    if "spotify_last_album_name" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_last_album_name",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "spotify_token_expires_at" not in columns:
        op.add_column(
            "users",
            sa.Column(
                "spotify_token_expires_at",
                postgresql.TIMESTAMP(timezone=True),
                autoincrement=False,
                nullable=True,
            ),
        )
    if "ix_users_webauthn_id" in users_indexes:
        op.drop_index(op.f("ix_users_webauthn_id"), table_name="users")
    if "ix_users_spotify_user_id" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_user_id"), "users", ["spotify_user_id"], unique=True
        )
    if "ix_users_spotify_token_expires_at" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_token_expires_at"),
            "users",
            ["spotify_token_expires_at"],
            unique=False,
        )
    if "ix_users_spotify_last_track_id" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_last_track_id"),
            "users",
            ["spotify_last_track_id"],
            unique=False,
        )
    if "ix_users_spotify_last_checked_at" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_last_checked_at"),
            "users",
            ["spotify_last_checked_at"],
            unique=False,
        )
    if "ix_users_spotify_is_playing" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_is_playing"),
            "users",
            ["spotify_is_playing"],
            unique=False,
        )
    if "ix_users_spotify_is_connected" not in users_indexes:
        op.create_index(
            op.f("ix_users_spotify_is_connected"),
            "users",
            ["spotify_is_connected"],
            unique=False,
        )
    if "webauthn_id" in columns:
        op.drop_column("users", "webauthn_id")
    if "ix_data_access_logs_subject_user_id" in dal_indexes:
        op.drop_index(
            op.f("ix_data_access_logs_subject_user_id"), table_name="data_access_logs"
        )
    if "ix_data_access_logs_resource_type" in dal_indexes:
        op.drop_index(
            op.f("ix_data_access_logs_resource_type"), table_name="data_access_logs"
        )
    if "ix_data_access_logs_resource_id" in dal_indexes:
        op.drop_index(
            op.f("ix_data_access_logs_resource_id"), table_name="data_access_logs"
        )
    if "ix_data_access_logs_actor_user_id" in dal_indexes:
        op.drop_index(
            op.f("ix_data_access_logs_actor_user_id"), table_name="data_access_logs"
        )
    if "ix_data_access_logs_action" in dal_indexes:
        op.drop_index(op.f("ix_data_access_logs_action"), table_name="data_access_logs")
    if "ix_data_access_logs_subject" not in dal_indexes:
        op.create_index(
            op.f("ix_data_access_logs_subject"),
            "data_access_logs",
            ["subject_user_id"],
            unique=False,
        )
    if "ix_data_access_logs_resource" not in dal_indexes:
        op.create_index(
            op.f("ix_data_access_logs_resource"),
            "data_access_logs",
            ["resource_type", "resource_id"],
            unique=False,
        )
    if "ix_data_access_logs_actor" not in dal_indexes:
        op.create_index(
            op.f("ix_data_access_logs_actor"),
            "data_access_logs",
            ["actor_user_id"],
            unique=False,
        )
    op.alter_column(
        "data_access_logs",
        "context",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("webauthn_credentials"):
        op.drop_index(
            op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials"
        )
        op.drop_index(
            op.f("ix_webauthn_credentials_credential_id"),
            table_name="webauthn_credentials",
        )
        op.drop_table("webauthn_credentials")
    # ### end Alembic commands ###
