"""add_webauthn_support_v2

Revision ID: ab93b27831f3
Revises: 202512210001
Create Date: 2025-12-21 11:04:32.338729

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab93b27831f3"
down_revision: str | None = "202512210001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite - this migration uses PostgreSQL-specific types and DROP COLUMN
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "webauthn_credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.String(), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("transports", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("backing_up", sa.Boolean(), nullable=True),
        sa.Column("backup_state", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webauthn_credentials_credential_id"),
        "webauthn_credentials",
        ["credential_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webauthn_credentials_user_id"),
        "webauthn_credentials",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "data_access_logs",
        "context",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_data_access_logs_actor"), table_name="data_access_logs")
    op.drop_index(op.f("ix_data_access_logs_resource"), table_name="data_access_logs")
    op.drop_index(op.f("ix_data_access_logs_subject"), table_name="data_access_logs")
    op.create_index(
        op.f("ix_data_access_logs_action"), "data_access_logs", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_data_access_logs_actor_user_id"),
        "data_access_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_access_logs_resource_id"),
        "data_access_logs",
        ["resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_access_logs_resource_type"),
        "data_access_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_access_logs_subject_user_id"),
        "data_access_logs",
        ["subject_user_id"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("webauthn_id", sa.String(length=128), nullable=True)
    )
    op.drop_index(op.f("ix_users_spotify_is_connected"), table_name="users")
    op.drop_index(op.f("ix_users_spotify_is_playing"), table_name="users")
    op.drop_index(op.f("ix_users_spotify_last_checked_at"), table_name="users")
    op.drop_index(op.f("ix_users_spotify_last_track_id"), table_name="users")
    op.drop_index(op.f("ix_users_spotify_token_expires_at"), table_name="users")
    op.drop_index(op.f("ix_users_spotify_user_id"), table_name="users")
    op.create_index(op.f("ix_users_webauthn_id"), "users", ["webauthn_id"], unique=True)
    op.drop_column("users", "spotify_token_expires_at")
    op.drop_column("users", "spotify_last_album_name")
    op.drop_column("users", "spotify_access_token")
    op.drop_column("users", "spotify_is_connected")
    op.drop_column("users", "spotify_refresh_token")
    op.drop_column("users", "spotify_last_track_id")
    op.drop_column("users", "spotify_last_track_name")
    op.drop_column("users", "spotify_user_id")
    op.drop_column("users", "spotify_last_track_url")
    op.drop_column("users", "spotify_is_playing")
    op.drop_column("users", "spotify_last_checked_at")
    op.drop_column("users", "spotify_last_album_image_url")
    op.drop_column("users", "spotify_last_artist_name")
    op.drop_column("users", "spotify_scope")
    op.drop_column("users", "spotify_display_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()

    # Skip on SQLite
    if bind.dialect.name == "sqlite":
        return

    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        "users",
        sa.Column(
            "spotify_display_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("spotify_scope", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_artist_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_album_image_url",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_checked_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_is_playing",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_track_url", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column("spotify_user_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_track_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_track_id", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_refresh_token", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_is_connected",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_access_token", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_last_album_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "spotify_token_expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_users_webauthn_id"), table_name="users")
    op.create_index(
        op.f("ix_users_spotify_user_id"), "users", ["spotify_user_id"], unique=True
    )
    op.create_index(
        op.f("ix_users_spotify_token_expires_at"),
        "users",
        ["spotify_token_expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_spotify_last_track_id"),
        "users",
        ["spotify_last_track_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_spotify_last_checked_at"),
        "users",
        ["spotify_last_checked_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_spotify_is_playing"),
        "users",
        ["spotify_is_playing"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_spotify_is_connected"),
        "users",
        ["spotify_is_connected"],
        unique=False,
    )
    op.drop_column("users", "webauthn_id")
    op.drop_index(
        op.f("ix_data_access_logs_subject_user_id"), table_name="data_access_logs"
    )
    op.drop_index(
        op.f("ix_data_access_logs_resource_type"), table_name="data_access_logs"
    )
    op.drop_index(
        op.f("ix_data_access_logs_resource_id"), table_name="data_access_logs"
    )
    op.drop_index(
        op.f("ix_data_access_logs_actor_user_id"), table_name="data_access_logs"
    )
    op.drop_index(op.f("ix_data_access_logs_action"), table_name="data_access_logs")
    op.create_index(
        op.f("ix_data_access_logs_subject"),
        "data_access_logs",
        ["subject_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_access_logs_resource"),
        "data_access_logs",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_access_logs_actor"),
        "data_access_logs",
        ["actor_user_id"],
        unique=False,
    )
    op.alter_column(
        "data_access_logs",
        "context",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_user_id"), table_name="webauthn_credentials"
    )
    op.drop_index(
        op.f("ix_webauthn_credentials_credential_id"), table_name="webauthn_credentials"
    )
    op.drop_table("webauthn_credentials")
    # ### end Alembic commands ###
