"""add attachments

Revision ID: b85f4f3edc89
Revises: fix_sender_id_type
Create Date: 2025-11-23 17:29:22.576198

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b85f4f3edc89"
down_revision: str | None = "fix_sender_id_type"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
