"""add_trusted_devices

Revision ID: db31ef5d7ea4
Revises: 202509250001
Create Date: 2025-11-22 18:33:24.370728

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db31ef5d7ea4"
down_revision: str | None = "202509250001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # Check if this is a fresh database with tables created via
    # Base.metadata.create_all. If so, skip these alterations as the
    # tables already have the correct schema.
    inspector = sa.inspect(bind)
    if "event_attendance" not in inspector.get_table_names():
        return

    op.drop_constraint(
        op.f("uq_active_sessions_jti"), "active_sessions", type_="unique"
    )
    op.alter_column(
        "event_attendance",
        "registered_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "events",
        "starts_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "ends_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(
        op.f("ix_events_search_vector"), table_name="events", postgresql_using="gin"
    )
    op.alter_column(
        "invite_codes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_mfa_challenges_session_id"), table_name="mfa_challenges")
    op.alter_column(
        "news",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_news_published_at_desc"), table_name="news")
    op.add_column(
        "notification_deliveries", sa.Column("status_code", sa.Integer(), nullable=True)
    )
    op.add_column(
        "notification_deliveries", sa.Column("detail", sa.Text(), nullable=True)
    )
    op.alter_column(
        "notification_deliveries",
        "delivered_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "read_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_notifications_dedupe_key"),
        "notifications",
        ["dedupe_key"],
        unique=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "push_subscriptions", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "push_subscriptions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_index(op.f("ix_push_subscriptions_active"), table_name="push_subscriptions")
    op.drop_index(
        op.f("ix_push_subscriptions_updated_at"), table_name="push_subscriptions"
    )
    op.create_index(
        op.f("ix_push_subscriptions_last_seen_at"),
        "push_subscriptions",
        ["last_seen_at"],
        unique=False,
    )
    op.drop_constraint(
        op.f("push_subscriptions_user_id_fkey"),
        "push_subscriptions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "push_subscriptions", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("push_subscriptions", "updated_at")
    op.drop_column("push_subscriptions", "active")
    op.alter_column(
        "schedule",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "schedule",
        "end_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_schedule_group_week_parity_date"), table_name="schedule")
    op.drop_index(op.f("ix_user_push_topics_updated_at"), table_name="user_push_topics")
    op.create_index(
        op.f("ix_user_push_topics_user_id"),
        "user_push_topics",
        ["user_id"],
        unique=False,
    )
    op.alter_column(
        "users",
        "spotify_token_expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "spotify_last_checked_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.drop_index(op.f("ux_users_lower_email"), table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return

    # Check if this is a fresh database - skip if users table doesn't exist
    # or doesn't have the columns we expect to modify
    inspector = sa.inspect(bind)
    existing_tables = set(inspector.get_table_names())
    if "users" not in existing_tables:
        return

    # Check if index already exists to avoid DuplicateTableError
    indexes = {ix["name"] for ix in inspector.get_indexes("users")}
    if "ux_users_lower_email" not in indexes:
        op.create_index(
            op.f("ux_users_lower_email"),
            "users",
            [sa.literal_column("lower(email::text)")],
            unique=True,
        )
    op.alter_column(
        "users",
        "spotify_last_checked_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "spotify_token_expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_user_push_topics_user_id"), table_name="user_push_topics")
    op.create_index(
        op.f("ix_user_push_topics_updated_at"),
        "user_push_topics",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_schedule_group_week_parity_date"),
        "schedule",
        ["group_id", "parity", "start_time"],
        unique=False,
    )
    op.alter_column(
        "schedule",
        "end_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "schedule",
        "start_time",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.add_column(
        "push_subscriptions",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "push_subscriptions",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "push_subscriptions", type_="foreignkey")
    op.create_foreign_key(
        op.f("push_subscriptions_user_id_fkey"),
        "push_subscriptions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_index(
        op.f("ix_push_subscriptions_last_seen_at"), table_name="push_subscriptions"
    )
    op.create_index(
        op.f("ix_push_subscriptions_updated_at"),
        "push_subscriptions",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_push_subscriptions_active"),
        "push_subscriptions",
        ["active"],
        unique=False,
    )
    op.alter_column(
        "push_subscriptions",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "push_subscriptions", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "password_reset_tokens",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "password_reset_tokens",
        "expires_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_notifications_dedupe_key"), table_name="notifications")
    op.alter_column(
        "notifications",
        "read_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "notifications",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "notification_deliveries",
        "delivered_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.drop_column("notification_deliveries", "detail")
    op.drop_column("notification_deliveries", "status_code")
    op.create_index(
        op.f("ix_news_published_at_desc"),
        "news",
        [sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.alter_column(
        "news",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        op.f("ix_mfa_challenges_session_id"),
        "mfa_challenges",
        ["session_id"],
        unique=False,
    )
    op.alter_column(
        "invite_codes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_events_search_vector"),
        "events",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.alter_column(
        "events",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "events",
        "ends_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "events",
        "starts_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "event_attendance",
        "registered_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.create_unique_constraint(
        op.f("uq_active_sessions_jti"),
        "active_sessions",
        ["jti"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
