"""Add stored_events table for domain event sourcing

Revision ID: f7aa476e968a
Revises: 202601130003
Create Date: 2026-01-13 23:10:51.446825

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7aa476e968a"
down_revision: str | None = "202601130003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stored_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stored_events_aggregate_id"),
        "stored_events",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_events_aggregate_type"),
        "stored_events",
        ["aggregate_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_events_created_at"),
        "stored_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stored_events_event_type"),
        "stored_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(op.f("ix_stored_events_id"), "stored_events", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if "stored_events" not in inspector.get_table_names():
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stored_events_id"), table_name="stored_events")
    op.drop_index(op.f("ix_stored_events_event_type"), table_name="stored_events")
    op.drop_index(op.f("ix_stored_events_created_at"), table_name="stored_events")
    op.drop_index(op.f("ix_stored_events_aggregate_type"), table_name="stored_events")
    op.drop_index(op.f("ix_stored_events_aggregate_id"), table_name="stored_events")
    op.drop_table("stored_events")
    # ### end Alembic commands ###
