apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: gateway-backend-disconnect
spec:
  action: partition
  mode: all
  selector:
    labelSelectors:
      app.kubernetes.io/name: gateway
  direction: both
  target:
    mode: all
    selector:
      labelSelectors:
        app.kubernetes.io/name: backend
  duration: "30s"
