{{- if and .Values.gateway.autoscaling.enabled (not (and .Values.keda.enabled .Values.hibernation.enabled .Values.hibernation.workloads.gateway.enabled)) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "university-ecosystem.fullname" . }}-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "university-ecosystem.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "university-ecosystem.fullname" . }}-gateway
  minReplicas: {{ .Values.gateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.gateway.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.gateway.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.gateway.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.gateway.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
