/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AdminRouteImport } from "./routes/_admin"
import { Route as AuthRouteImport } from "./routes/_auth"
import { Route as PublicRouteImport } from "./routes/_public"
import { Route as AuthActivityRouteImport } from "./routes/_auth/activity"
import { Route as AuthDashboardRouteImport } from "./routes/_auth/dashboard"
import { Route as AuthMapRouteImport } from "./routes/_auth/map"
import { Route as AuthMessengerRouteImport } from "./routes/_auth/messenger"
import { Route as AuthProfileRouteImport } from "./routes/_auth/profile"
import { Route as AuthScheduleRouteImport } from "./routes/_auth/schedule"
import { Route as AuthSettingsRouteImport } from "./routes/_auth/settings"
import { Route as PublicForgotPasswordRouteImport } from "./routes/_public/forgot-password"
import { Route as PublicLoginRouteImport } from "./routes/_public/login"
import { Route as PublicRegisterRouteImport } from "./routes/_public/register"
import { Route as PublicResetPasswordRouteImport } from "./routes/_public/reset-password"
import { Route as AdminAdminAuditRouteImport } from "./routes/_admin/admin.audit"
import { Route as AdminAdminFeatureFlagsRouteImport } from "./routes/_admin/admin.feature-flags"
import { Route as AdminAdminNotificationsRouteImport } from "./routes/_admin/admin.notifications"
import { Route as AdminAdminStoriesRouteImport } from "./routes/_admin/admin.stories"
import { Route as AdminAdminUsersRouteImport } from "./routes/_admin/admin.users"
import { Route as AuthEventsIndexRouteImport } from "./routes/_auth/events.index"
import { Route as AuthEventsIdRouteImport } from "./routes/_auth/events.$id"
import { Route as AuthMessengerChatIdRouteImport } from "./routes/_auth/messenger.$chatId"
import { Route as AuthNewsIndexRouteImport } from "./routes/_auth/news.index"
import { Route as AuthNewsIdRouteImport } from "./routes/_auth/news.$id"
import { Route as PublicResetPasswordTokenRouteImport } from "./routes/_public/reset-password.$token"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: "/_admin",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthActivityRoute = AuthActivityRouteImport.update({
  id: "/activity",
  path: "/activity",
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthRoute,
} as any)
const AuthMapRoute = AuthMapRouteImport.update({
  id: "/map",
  path: "/map",
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessengerRoute = AuthMessengerRouteImport.update({
  id: "/messenger",
  path: "/messenger",
  getParentRoute: () => AuthRoute,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AuthRoute,
} as any)
const AuthScheduleRoute = AuthScheduleRouteImport.update({
  id: "/schedule",
  path: "/schedule",
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AuthRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => PublicRoute,
} as any)
const AdminAdminAuditRoute = AdminAdminAuditRouteImport.update({
  id: "/admin/audit",
  path: "/admin/audit",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeatureFlagsRoute = AdminAdminFeatureFlagsRouteImport.update({
  id: "/admin/feature-flags",
  path: "/admin/feature-flags",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: "/admin/notifications",
  path: "/admin/notifications",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminStoriesRoute = AdminAdminStoriesRouteImport.update({
  id: "/admin/stories",
  path: "/admin/stories",
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: "/admin/users",
  path: "/admin/users",
  getParentRoute: () => AdminRoute,
} as any)
const AuthEventsIndexRoute = AuthEventsIndexRouteImport.update({
  id: "/events/",
  path: "/events/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthEventsIdRoute = AuthEventsIdRouteImport.update({
  id: "/events/$id",
  path: "/events/$id",
  getParentRoute: () => AuthRoute,
} as any)
const AuthMessengerChatIdRoute = AuthMessengerChatIdRouteImport.update({
  id: "/$chatId",
  path: "/$chatId",
  getParentRoute: () => AuthMessengerRoute,
} as any)
const AuthNewsIndexRoute = AuthNewsIndexRouteImport.update({
  id: "/news/",
  path: "/news/",
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsIdRoute = AuthNewsIdRouteImport.update({
  id: "/news/$id",
  path: "/news/$id",
  getParentRoute: () => AuthRoute,
} as any)
const PublicResetPasswordTokenRoute =
  PublicResetPasswordTokenRouteImport.update({
    id: "/$token",
    path: "/$token",
    getParentRoute: () => PublicResetPasswordRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/activity": typeof AuthActivityRoute
  "/dashboard": typeof AuthDashboardRoute
  "/map": typeof AuthMapRoute
  "/messenger": typeof AuthMessengerRouteWithChildren
  "/profile": typeof AuthProfileRoute
  "/schedule": typeof AuthScheduleRoute
  "/settings": typeof AuthSettingsRoute
  "/forgot-password": typeof PublicForgotPasswordRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
  "/reset-password": typeof PublicResetPasswordRouteWithChildren
  "/admin/audit": typeof AdminAdminAuditRoute
  "/admin/feature-flags": typeof AdminAdminFeatureFlagsRoute
  "/admin/notifications": typeof AdminAdminNotificationsRoute
  "/admin/stories": typeof AdminAdminStoriesRoute
  "/admin/users": typeof AdminAdminUsersRoute
  "/events/$id": typeof AuthEventsIdRoute
  "/messenger/$chatId": typeof AuthMessengerChatIdRoute
  "/news/$id": typeof AuthNewsIdRoute
  "/reset-password/$token": typeof PublicResetPasswordTokenRoute
  "/events/": typeof AuthEventsIndexRoute
  "/news/": typeof AuthNewsIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/activity": typeof AuthActivityRoute
  "/dashboard": typeof AuthDashboardRoute
  "/map": typeof AuthMapRoute
  "/messenger": typeof AuthMessengerRouteWithChildren
  "/profile": typeof AuthProfileRoute
  "/schedule": typeof AuthScheduleRoute
  "/settings": typeof AuthSettingsRoute
  "/forgot-password": typeof PublicForgotPasswordRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
  "/reset-password": typeof PublicResetPasswordRouteWithChildren
  "/admin/audit": typeof AdminAdminAuditRoute
  "/admin/feature-flags": typeof AdminAdminFeatureFlagsRoute
  "/admin/notifications": typeof AdminAdminNotificationsRoute
  "/admin/stories": typeof AdminAdminStoriesRoute
  "/admin/users": typeof AdminAdminUsersRoute
  "/events/$id": typeof AuthEventsIdRoute
  "/messenger/$chatId": typeof AuthMessengerChatIdRoute
  "/news/$id": typeof AuthNewsIdRoute
  "/reset-password/$token": typeof PublicResetPasswordTokenRoute
  "/events": typeof AuthEventsIndexRoute
  "/news": typeof AuthNewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_admin": typeof AdminRouteWithChildren
  "/_auth": typeof AuthRouteWithChildren
  "/_public": typeof PublicRouteWithChildren
  "/_auth/activity": typeof AuthActivityRoute
  "/_auth/dashboard": typeof AuthDashboardRoute
  "/_auth/map": typeof AuthMapRoute
  "/_auth/messenger": typeof AuthMessengerRouteWithChildren
  "/_auth/profile": typeof AuthProfileRoute
  "/_auth/schedule": typeof AuthScheduleRoute
  "/_auth/settings": typeof AuthSettingsRoute
  "/_public/forgot-password": typeof PublicForgotPasswordRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/register": typeof PublicRegisterRoute
  "/_public/reset-password": typeof PublicResetPasswordRouteWithChildren
  "/_admin/admin/audit": typeof AdminAdminAuditRoute
  "/_admin/admin/feature-flags": typeof AdminAdminFeatureFlagsRoute
  "/_admin/admin/notifications": typeof AdminAdminNotificationsRoute
  "/_admin/admin/stories": typeof AdminAdminStoriesRoute
  "/_admin/admin/users": typeof AdminAdminUsersRoute
  "/_auth/events/$id": typeof AuthEventsIdRoute
  "/_auth/messenger/$chatId": typeof AuthMessengerChatIdRoute
  "/_auth/news/$id": typeof AuthNewsIdRoute
  "/_public/reset-password/$token": typeof PublicResetPasswordTokenRoute
  "/_auth/events/": typeof AuthEventsIndexRoute
  "/_auth/news/": typeof AuthNewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/activity"
    | "/dashboard"
    | "/map"
    | "/messenger"
    | "/profile"
    | "/schedule"
    | "/settings"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/admin/audit"
    | "/admin/feature-flags"
    | "/admin/notifications"
    | "/admin/stories"
    | "/admin/users"
    | "/events/$id"
    | "/messenger/$chatId"
    | "/news/$id"
    | "/reset-password/$token"
    | "/events/"
    | "/news/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/activity"
    | "/dashboard"
    | "/map"
    | "/messenger"
    | "/profile"
    | "/schedule"
    | "/settings"
    | "/forgot-password"
    | "/login"
    | "/register"
    | "/reset-password"
    | "/admin/audit"
    | "/admin/feature-flags"
    | "/admin/notifications"
    | "/admin/stories"
    | "/admin/users"
    | "/events/$id"
    | "/messenger/$chatId"
    | "/news/$id"
    | "/reset-password/$token"
    | "/events"
    | "/news"
  id:
    | "__root__"
    | "/"
    | "/_admin"
    | "/_auth"
    | "/_public"
    | "/_auth/activity"
    | "/_auth/dashboard"
    | "/_auth/map"
    | "/_auth/messenger"
    | "/_auth/profile"
    | "/_auth/schedule"
    | "/_auth/settings"
    | "/_public/forgot-password"
    | "/_public/login"
    | "/_public/register"
    | "/_public/reset-password"
    | "/_admin/admin/audit"
    | "/_admin/admin/feature-flags"
    | "/_admin/admin/notifications"
    | "/_admin/admin/stories"
    | "/_admin/admin/users"
    | "/_auth/events/$id"
    | "/_auth/messenger/$chatId"
    | "/_auth/news/$id"
    | "/_public/reset-password/$token"
    | "/_auth/events/"
    | "/_auth/news/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_admin": {
      id: "/_admin"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth": {
      id: "/_auth"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_auth/activity": {
      id: "/_auth/activity"
      path: "/activity"
      fullPath: "/activity"
      preLoaderRoute: typeof AuthActivityRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/dashboard": {
      id: "/_auth/dashboard"
      path: "/dashboard"
      fullPath: "/dashboard"
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/map": {
      id: "/_auth/map"
      path: "/map"
      fullPath: "/map"
      preLoaderRoute: typeof AuthMapRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/messenger": {
      id: "/_auth/messenger"
      path: "/messenger"
      fullPath: "/messenger"
      preLoaderRoute: typeof AuthMessengerRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/profile": {
      id: "/_auth/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/schedule": {
      id: "/_auth/schedule"
      path: "/schedule"
      fullPath: "/schedule"
      preLoaderRoute: typeof AuthScheduleRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/settings": {
      id: "/_auth/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_public/forgot-password": {
      id: "/_public/forgot-password"
      path: "/forgot-password"
      fullPath: "/forgot-password"
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/register": {
      id: "/_public/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/reset-password": {
      id: "/_public/reset-password"
      path: "/reset-password"
      fullPath: "/reset-password"
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_admin/admin/audit": {
      id: "/_admin/admin/audit"
      path: "/admin/audit"
      fullPath: "/admin/audit"
      preLoaderRoute: typeof AdminAdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_admin/admin/feature-flags": {
      id: "/_admin/admin/feature-flags"
      path: "/admin/feature-flags"
      fullPath: "/admin/feature-flags"
      preLoaderRoute: typeof AdminAdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_admin/admin/notifications": {
      id: "/_admin/admin/notifications"
      path: "/admin/notifications"
      fullPath: "/admin/notifications"
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_admin/admin/stories": {
      id: "/_admin/admin/stories"
      path: "/admin/stories"
      fullPath: "/admin/stories"
      preLoaderRoute: typeof AdminAdminStoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_admin/admin/users": {
      id: "/_admin/admin/users"
      path: "/admin/users"
      fullPath: "/admin/users"
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    "/_auth/events/": {
      id: "/_auth/events/"
      path: "/events"
      fullPath: "/events/"
      preLoaderRoute: typeof AuthEventsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/events/$id": {
      id: "/_auth/events/$id"
      path: "/events/$id"
      fullPath: "/events/$id"
      preLoaderRoute: typeof AuthEventsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/messenger/$chatId": {
      id: "/_auth/messenger/$chatId"
      path: "/$chatId"
      fullPath: "/messenger/$chatId"
      preLoaderRoute: typeof AuthMessengerChatIdRouteImport
      parentRoute: typeof AuthMessengerRoute
    }
    "/_auth/news/": {
      id: "/_auth/news/"
      path: "/news"
      fullPath: "/news/"
      preLoaderRoute: typeof AuthNewsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_auth/news/$id": {
      id: "/_auth/news/$id"
      path: "/news/$id"
      fullPath: "/news/$id"
      preLoaderRoute: typeof AuthNewsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    "/_public/reset-password/$token": {
      id: "/_public/reset-password/$token"
      path: "/$token"
      fullPath: "/reset-password/$token"
      preLoaderRoute: typeof PublicResetPasswordTokenRouteImport
      parentRoute: typeof PublicResetPasswordRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminAuditRoute: typeof AdminAdminAuditRoute
  AdminAdminFeatureFlagsRoute: typeof AdminAdminFeatureFlagsRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminStoriesRoute: typeof AdminAdminStoriesRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminAuditRoute: AdminAdminAuditRoute,
  AdminAdminFeatureFlagsRoute: AdminAdminFeatureFlagsRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminStoriesRoute: AdminAdminStoriesRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthMessengerRouteChildren {
  AuthMessengerChatIdRoute: typeof AuthMessengerChatIdRoute
}

const AuthMessengerRouteChildren: AuthMessengerRouteChildren = {
  AuthMessengerChatIdRoute: AuthMessengerChatIdRoute,
}

const AuthMessengerRouteWithChildren = AuthMessengerRoute._addFileChildren(
  AuthMessengerRouteChildren,
)

interface AuthRouteChildren {
  AuthActivityRoute: typeof AuthActivityRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthMapRoute: typeof AuthMapRoute
  AuthMessengerRoute: typeof AuthMessengerRouteWithChildren
  AuthProfileRoute: typeof AuthProfileRoute
  AuthScheduleRoute: typeof AuthScheduleRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthEventsIdRoute: typeof AuthEventsIdRoute
  AuthNewsIdRoute: typeof AuthNewsIdRoute
  AuthEventsIndexRoute: typeof AuthEventsIndexRoute
  AuthNewsIndexRoute: typeof AuthNewsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivityRoute: AuthActivityRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthMapRoute: AuthMapRoute,
  AuthMessengerRoute: AuthMessengerRouteWithChildren,
  AuthProfileRoute: AuthProfileRoute,
  AuthScheduleRoute: AuthScheduleRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthEventsIdRoute: AuthEventsIdRoute,
  AuthNewsIdRoute: AuthNewsIdRoute,
  AuthEventsIndexRoute: AuthEventsIndexRoute,
  AuthNewsIndexRoute: AuthNewsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicResetPasswordRouteChildren {
  PublicResetPasswordTokenRoute: typeof PublicResetPasswordTokenRoute
}

const PublicResetPasswordRouteChildren: PublicResetPasswordRouteChildren = {
  PublicResetPasswordTokenRoute: PublicResetPasswordTokenRoute,
}

const PublicResetPasswordRouteWithChildren =
  PublicResetPasswordRoute._addFileChildren(PublicResetPasswordRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRouteWithChildren
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRouteWithChildren,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.ts"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
