homepage: "https://github.com/university-ecosystem"
language: rust
primary_contact: "security@university-ecosystem.local"
auto_ccs:
  - security@university-ecosystem.local
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
sanitizers:
  - address
  - undefined
arcitectures:
  - x86_64
