"""add lesson_type to schedule

Revision ID: 30fa2627aa5e
Revises: 4fa4374013f3
Create Date: 2025-06-01 12:30:15.217983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fa2627aa5e'
down_revision: Union[str, None] = '4fa4374013f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('lesson_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'lesson_type')
    # ### end Alembic commands ###
