"""add_signature_to_data_access_logs

Revision ID: 31e81f57c53d
Revises: ab93b27831f3
Create Date: 2025-12-21 21:46:39.483334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e81f57c53d'
down_revision: Union[str, None] = 'ab93b27831f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_access_logs', sa.Column('signature', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_access_logs', 'signature')
    # ### end Alembic commands ###
