"""add is_used to invite_codes

Revision ID: 6bdc356a128b
Revises: a4bfc1ba3076
Create Date: 2025-05-31 16:57:52.071516

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6bdc356a128b"
down_revision: Union[str, None] = "a4bfc1ba3076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invite_codes", sa.Column("is_used", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invite_codes", "is_used")
    # ### end Alembic commands ###
