"""delete personal schedule

Revision ID: 7ad8a9a11478
Revises: 2bc18c38157c
Create Date: 2025-06-01 02:55:47.045867

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ad8a9a11478"
down_revision: Union[str, None] = "2bc18c38157c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("personal_schedule")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_schedule",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("subject", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("teacher", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("room", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("weekday", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "start_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "end_time", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="personal_schedule_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="personal_schedule_pkey"),
    )
    # ### end Alembic commands ###
