"""add speaker and photo_url to events

Revision ID: 7db0b7a03e37
Revises: 30fa2627aa5e
Create Date: 2025-06-02 17:03:26.759896

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7db0b7a03e37"
down_revision: Union[str, None] = "30fa2627aa5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("speaker", sa.String(), nullable=True))
    op.add_column("events", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "image_url")
    op.drop_column("events", "speaker")
    # ### end Alembic commands ###
