"""add about to event

Revision ID: 7ea701e08870
Revises: 7db0b7a03e37
Create Date: 2025-06-04 01:08:34.347366

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ea701e08870"
down_revision: Union[str, None] = "7db0b7a03e37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("about", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "about")
    # ### end Alembic commands ###
