"""add_chat_models

Revision ID: 96809b6dc35d
Revises: db31ef5d7ea4
Create Date: 2025-11-23 02:13:08.270568

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "96809b6dc35d"
down_revision: str | None = "db31ef5d7ea4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
