name: Backend tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  pytest:
    name: Pytest with coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest --cov=app --cov-report=xml --cov-report=term-missing
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-xml
          path: root/coverage.xml
          if-no-files-found: warn
