name: CI
on: [push, pull_request]

jobs:
  node:
    if: ${{ hashFiles('**/package.json') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - run: |
          if [ -f package-lock.json ]; then npm ci; else npm install; fi
      - run: npm run build --if-present
      - run: npm test --if-present

  python:
    if: ${{ hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install .; fi
      - run: |
          if compgen -G "tests/**" > /dev/null; then pytest -q; else echo "No tests/"; fi
