name: Gitleaks

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}

  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.78.1
        with:
          path: .
          base: ""
          extra_args: --exclude-detectors=Codeclimate --exclude-secrets=.trufflehog-exclude-secrets.txt --exclude-paths=.trufflehog-exclude-paths.txt
