name: "Semantic PR Title Check"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Pull Request Title check
        uses: amannn/action-semantic-pull-request@e9f87f9856ad43b9b488f7734bbd826a791a8e1e # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Types allowed under Conventional Commits
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
