name: "Semantic PR Title Check"
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  main:
    name: Validate PR Title
    runs-on: ubuntu-24.04
    steps:
      - name: Semantic Pull Request Title check
        uses: amannn/action-semantic-pull-request@2c9480cf285c2ac02b52e26013f7d627b14a4f95 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Types allowed under Conventional Commits
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          requireScope: false
