from __future__ import annotations

import uuid
from typing import Protocol, runtime_checkable


@runtime_checkable
class UserLike(Protocol):
    """
    Protocol for objects that behave like a User in the context of email updates.
    This allows both ORM entities and DTOs to be handled by the same logic.
    """

    id: uuid.UUID
    pending_email: str | None


@runtime_checkable
class DatabaseSession(Protocol):
    """Sync session protocol (for completeness if needed)."""

    def execute(self, statement: Any, params: Any = None, **kwargs: Any) -> Any: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def add(self, instance: Any) -> None: ...
    def flush(self, objects: Any = None) -> None: ...
    def refresh(
        self, instance: Any, attribute_names: Any = None, **kwargs: Any
    ) -> None: ...


@runtime_checkable
class AsyncDatabaseSession(Protocol):
    """Async session protocol (TD-3: audit 2026-02-24)."""

    async def execute(self, statement: Any, params: Any = None, **kwargs: Any) -> Any: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    def add(self, instance: Any) -> None: ...
    def add_all(self, instances: Iterable[Any]) -> None: ...
    async def flush(self, objects: Any = None) -> None: ...
    async def refresh(
        self, instance: Any, attribute_names: Any = None, **kwargs: Any
    ) -> None: ...
    async def delete(self, instance: Any) -> None: ...
    async def get(self, entity: Any, ident: Any, **kwargs: Any) -> Any | None: ...
    async def scalar(self, statement: Any, params: Any = None, **kwargs: Any) -> Any: ...
    async def scalars(self, statement: Any, params: Any = None, **kwargs: Any) -> Any: ...
    async def close(self) -> None: ...
